### ISSUE TITLE
Not works on Docker Mac Native - Zookeeper timeouts

### ISSUE THREAD

**Issue by abtris** [wurstmeister/kafka-docker#110]
I'm using Docker Native with 6GB RAM, 2CPU Core.

``` shell
$ docker -v
Docker version 1.12.0, build 8eab29e
```
- `kafka_2.11-0.10.0.0, zookeeper-3.4.6`

I try make steps in [help](http://wurstmeister.github.io/kafka-docker/) for testing.

``` shell
$ docker-compose up -d
$ docker-compose scale kafka=2
$ ./start-kafka-shell.sh 172.18.0.2 172.18.0.3:2181
bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --create --topic topic \
> --partitions 4 --zookeeper $ZK --replication-factor 2
Exception in thread "main" org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
    at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1232)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:156)
    at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:130)
    at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:75)
    at kafka.utils.ZkUtils$.apply(ZkUtils.scala:57)
    at kafka.admin.TopicCommand$.main(TopicCommand.scala:54)
    at kafka.admin.TopicCommand.main(TopicCommand.scala)
```

Any idea why this not work?
It's some simple test for zookeeper how check if works correctly?
IP Addresses are from `docker inspect`

**Comment by jonbuffington** [comment]
Most likely the broker's advertised IP address is incorrect. I use an environment variable,  DOCKER_HOST_IP, to use my Mac's public IP address as the KAFKA_ADVERTISED_HOST_NAME value. Here are the relevant snippets from my scripts:

…
```shell
#
# Set the docker-compose.yml variable
#
if [[ -z "${DOCKER_HOST_IP-}" ]]; then
  docker_host_ip=$(docker run --rm --net host alpine ip address show eth0 | awk#
  # Work around Docker for Mac 1.12.0-rc2-beta16 (build: 9493)
  if [[ $docker_host_ip = '192.168.65.2' ]]; then
    docker_host_ip=$(/sbin/ifconfig | grep -v '127.0.0.1' | awk '$1=="inet" {pr#
  fi
  export DOCKER_HOST_IP=$docker_host_ip
fi
echo "DOCKER_HOST_IP=${DOCKER_HOST_IP}"
```
…

…
```YAML
  kafka:
    image: wurstmeister/kafka:0.9.0.1
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_HOST_IP}"
      KAFKA_ZOOKEEPER_CONNECT: zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
…

**Comment by VatslavDS** [comment]
@jonbuffington where do you place your .bash code?

Thank you.

**Comment by jonbuffington** [comment]
@VatslavDS I created a script, `bootstrap.sh`, that executes the above then then `docker-compose up -d`. The script is in the same directory as the `docker-compose.yml` file although the script could be located anywhere including `.bash_profile`. The key part is to export `DOCKER_HOST_IP` to the shell that executes `docker-compose`.

**Comment by VatslavDS** [comment]
@jonbuffington but In which part do you call the script? only doing this? ""${DOCKER_HOST_IP}"?

**Comment by VatslavDS** [comment]
Can you share bootstrap.sh file please?

**Comment by sanear** [comment]
@jonbuffington Your script is truncated in some weird way, so the awk command terminates too early. If you'd upload, that would be pretty cool.

**Comment by jonbuffington** [comment]
@VatslavDS @sanear I updated the above comment with abbreviated content of the script.

**Comment by VatslavDS** [comment]
@jonbuffington I've already updated my boot.sh to your code, however when I try to publish and suscribe to that, it doesn't work (Even nor an error). Could you share your full docker-compose.yml ?

Thank you.

**Comment by mmullis** [comment]
Hi all.  I had some problems switching to the new mac native docker and found that --net=host is not working as I expected. 
Dropping the --net=host and individually mapping  the exposed ports with -p works perfectly.
Do it for both zk and kafka.
e.g.
 -p 9092:9092  for kafka

For Zookeeper, there's 3
-p 2181:2181 \
-p 2888:2888 \
-p 3888:3888 \

I hope that's on point for this problem and saves everyone some grief.

**Comment by tscholak** [comment]
@jonbuffington @VatslavDS @mmullis 

I find that nothing proposed here works.

My full `docker-compose.yml`:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKER_HOST_IP}"
      KAFKA_ZOOKEEPER_CONNECT: zk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
What sense does it make to set `KAFKA_ZOOKEEPER_CONNECT` to a link alias, i.e. `zk`?
