### ISSUE TITLE
JMX Connector error with Kafka-Manager

### ISSUE THREAD

**Issue by Paw2Pom** [wurstmeister/kafka-docker#123]
I am trying to enable the JMX Metrics on Kafka-Manager, however it seems the connection to docker kafka is not possible:

[error] k.m.j.KafkaJMX$ - Failed to connect to service:jmx:rmi:///jndi/rmi://192.168.1.110:9093/jmxrmi

The docker-compose file I am using is listed below. Does this mean the docker-kafka needs to install jmxtrans so that jmx connection to the docker container than become possible?

====
docker-compose
====

version: '2'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    build: .
    ports:
      - "9092"
      - "9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.110
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    links:
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein

**Comment by wurstmeister** [comment]
Hi, 

looks like your ports definition for kafka is not correct

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.110
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9093
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - "9000:9000"
    links:
      - zookeeper
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein 
```
