### ISSUE TITLE
Why the image does not bind the port 9092?

### ISSUE THREAD

**Issue by rolele** [wurstmeister/kafka-docker#135]
I am experiencing a problem with swarmkit and I think this is due to the image not exposing the port 9092. 
I am not sure yet, I created an issue https://github.com/docker/swarmkit/issues/1717

It seems to me that it is a common practice to expose the port the service is running on.
Any reason why kafka-docker is not exposing any port?

**Comment by oivoodoo** [comment]
Hi @rolele . I've just tried to run kafka-docker using `docker-compose.yml` for one of my applications by using this change:

```
  kafka:
    build: .
    ports:
      - "9092:9092"
```

**Comment by sirolf2009** [comment]
Docker assigns random ports to containers, unless specified as @oivoodoo has.
This poses a risk though, because when you fire up another one of these containers, it will fail because the port is already in use. So you'd have to remember to change the port each time you launch a new instance.

If you prefer to stick with random ports, you can use ```docker ps``` to see the mapped ports

**Comment by sscaling** [comment]
Please see readme and [docker-compose-swarm.yml](https://github.com/wurstmeister/kafka-docker/blob/master/docker-compose-swarm.yml) for info and examples about how to run on Swarm using an overlay network.

Please re-open if this doesn't resolve your issue.

**Comment by Wenzil** [comment]
In my case, the kafka container is accessible through 9092 even though I'm not explicitly publishing the 9092 port. Any idea why?

My use case is to run integration tests in a self-contained docker CI environment.

I'm using CircleCI's [Docker executor](https://circleci.com/docs/2.0/configuration-reference/#docker--machine--macosexecutor) where it's possible to set up a [multi-image configuration job](https://circleci.com/docs/2.0/executor-types/#using-multiple-docker-images) in the same docker network. However, from the docs, it's not possible to explicitly publish/expose specific ports (such as 9092 in kafka's case). So in theory I'm relying on ports exposed by the images' Dockerfiles.

I'm just baffled that my kafka integration tests still work despite not explicitly exposing port 9092...

Thoughts?

My CircleCI job config:

```yaml
test:
    docker:
        - image: node:9.6
            name: primary
            environment:
                PORT: 3005
                KAFKA_BROKER_LIST: kafka:9092

        - image: wurstmeister/kafka:latest
            name: kafka
            environment:
                KAFKA_ADVERTISED_HOST_NAME: kafka
                KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        - image: wurstmeister/zookeeper
            name: zookeeper
    steps:
        - checkout
        - run: yarn
        - run: yarn test
```
