### ISSUE TITLE
Got 'org.apache.kafka.common.errors.TimeoutException' when send message on linux Fedora25/CentOS7

### ISSUE THREAD

**Issue by derekey** [wurstmeister/kafka-docker#149]
It can't send message on Fedora25/CentOS7 but it works ok in Debian8

Fedora25

- env

1. uname

`Linux solution.localdomain 4.8.6-300.fc25.x86_64 #1 SMP Tue Nov 1 12:36:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

2. docker-compose version

```
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t 3 May 2016
```

3. docker version

```
Client:
Version: 1.12.5
API version: 1.24
Package version: docker-common-1.12.5-4.git03508cc.fc25.x86_64
Go version: go1.7.4
Git commit: 03508cc/1.12.5
Built: Thu Jan 5 00:59:17 2017
OS/Arch: linux/amd64
Server:
Version: 1.12.5
API version: 1.24
Package version: docker-common-1.12.5-4.git03508cc.fc25.x86_64
Go version: go1.7.4
Git commit: 03508cc/1.12.5
Built: Thu Jan 5 00:59:17 2017
OS/Arch: linux/amd64
```

4. docker-compose-single-broker.yml 

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.6.11.80
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

- error

kafka-console-producer.sh

```
[root@solution kafka-docker]# docker-compose run kafka /opt/kafka/bin/kafka-console-producer.sh --broker-list 10.6.11.80:9092 --topic test
1
[2017-01-09 09:26:37,223] ERROR Error when sending message to topic test with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
```

This looks very strange, How can I solve this problem? Thank a lot! @wurstmeister
