### ISSUE TITLE
Internal host wrong

### ISSUE THREAD

**Issue by b0c1** [wurstmeister/kafka-docker#17]
Hi!

I try to pull up kafka. I created two kafka instance and an another one named kafkaclient (linked to kafka instances). I try to run the 
```
 $KAFKA_HOME/bin/kafka-console-consumer.sh --topic=topic --zookeeper=$ZK_PORT_2181_TCP_ADDR
```

But I got:
```
[2014-11-10 10:11:08,628] WARN [console-consumer-92965_537adcb9a894-1415614259216-39d19909-leader-finder-thread], Failed to find leader for Set([topic,3], [topic,2], [topic,0], [topic,1]) (kafka.consumer.ConsumerFetcherManager$LeaderFinderThread)
kafka.common.KafkaException: fetching topic metadata for topics [Set(topic)] from broker [ArrayBuffer(id:49176,host:8042ab38dd44,port:49176, id:49175,host:df9514a03dca,port:49175)] failed
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:67)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:88)
        at kafka.consumer.ConsumerFetcherManager$LeaderFinderThread.doWork(ConsumerFetcherManager.scala:66)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:51)
Caused by: java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:89)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:514)
        at kafka.network.BlockingChannel.connect(BlockingChannel.scala:57)
        at kafka.producer.SyncProducer.connect(SyncProducer.scala:141)
        at kafka.producer.SyncProducer.getOrMakeConnection(SyncProducer.scala:156)
        at kafka.producer.SyncProducer.kafka$producer$SyncProducer$$doSend(SyncProducer.scala:68)
        at kafka.producer.SyncProducer.send(SyncProducer.scala:112)
        at kafka.client.ClientUtils$.fetchTopicMetadata(ClientUtils.scala:53)
        ... 3 more

```
It's can't resolve the host address provided by zk. In my custom application if I provide the broker metadata ip/port to the kafka client I got connection refused... any idea why?

**Comment by eudaimos** [comment]
@wurstmeister the only value I ever see being set for `KAFKA_ADVERTISED_HOST_NAME` is the default IP of boot2docker (`192.168.59.103`).  I am at a loss as to what to set it to when **not** running locally using boot2docker.

I've tried removing the `environment: KAFKA_ADVERTISED_HOST_NAME` which leads to:
- zookeeper stores the host as the generated host name from docker
- my custom container node.js apps cannot address the host with the metadata provided by zookeeper (like @b0c1), even if I `link` them within `fig.yml` -> _is there a way to provide a link name that will also be used as a hostname provided to zookeeper?_

I tried giving the kafka service in `fig.yml` a `hostname: kafkabroker` value which led to:
- kafka brokers can't start as it throws an error since it seems to expect HOSTNAME to be a number (likely the broker id)
- this occurs whether or not `KAFKA_ADVERTISED_HOST_NAME` is set

I tried giving setting `KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0` for the kafka service and it led to:
- connection refused just @b0c1

**Comment by eudaimos** [comment]
@b0c1 did you ever solve your problem?

**Comment by eudaimos** [comment]
Ok, documenting here so I hope it helps others - using the IP address from `ifconfig docker0` works to provide the right discoverability and connectivity between brokers, zookeeper, and external apps that are producers and consumers.

To isolate the ip I found this command from [here on StackOverflow](http://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach) and modified it for this purpose:
```Shell
export KAFKA_ADVERTISED_HOST_NAME=$(route -n | awk '/UG[ \t]/{print $2}')
```

Going to create a pull request eventually to get that into the startup script

**Comment by wurstmeister** [comment]
Hi, 

please check https://issues.apache.org/jira/browse/KAFKA-1092 regarding the ADVERTISED_HOST_NAME parameter. 

You should set this to the name/ip of the host that runs docker. If you run docker natively on a linux box, you can set this parameter to your host ip address (e.g. the IP of eth0), which will allow you to access kafka from other machines in the network. 

If you set it to your docker0 IP address you can only access kafka from the host that runs docker.

**Comment by denisgarci** [comment]
Hi,

Thanks for making this image! I'm also encountering this issue. The problem with setting ADVERTISED_HOST_NAME to the host ip (eth0 or wlan0) is that you need to open the ports on the host firewall. It's also a bit "ugly" in the sense that I would prefer my containers (that are all running on the same host) to be able to communicate through internal ips.

Maybe the default value of the ADVERTISED_HOST_NAME could be set to docker0 ip. The current behaviour (setting manually ADVERTISED_HOST_NAME) would still work. What do you think?

**Comment by krishna81m** [comment]
I explicitly set my eth0 address: 10.35.25.95 in docker-compose and still get connection refused, here is the proof on my Ubuntu 14.04:

```
./start-kafka-shell.sh 10.35.25.95 10.35.25.95:2181

bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --create --topic test-topic --partitions 10 --zookeeper $ZK --replication-factor 2
[2016-03-11 03:02:42,678] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

# ifconfig -a
docker0   Link encap:Ethernet  HWaddr 02:42:53:a1:0f:5c
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:53ff:fea1:f5c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:7360 errors:0 dropped:0 overruns:0 frame:0
          TX packets:24501 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:689071 (689.0 KB)  TX bytes:78237650 (78.2 MB)

eth0      Link encap:Ethernet  HWaddr 00:50:56:ae:3e:28
          inet addr:10.35.25.95  Bcast:10.30.20.255  Mask:255.255.254.0
          inet6 addr: fe80::250:56ff:feae:3e28/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:581330 errors:0 dropped:0 overruns:0 frame:0
          TX packets:66287 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000


docker inspect `LAST_CONT`
[
    {
        "Id": "4f3a80deede74d35c03cd90c57af5a0e897afa9ca49a460966e4e1cf0914325d",
        "Created": "2016-03-11T02:13:17.361467049Z",
        "Path": "start-kafka.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 28558,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-03-11T02:13:17.655398922Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:9cf1c187ee2bfed1c9268d26f3ecba7afb4782a24df1e1248ddb3d0531e600a5",
        "ResolvConfPath": "/var/lib/docker/containers/4f3a80deede74d35c03cd90c57af5a0e897afa9ca49a460966e4e1cf0914325d/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/4f3a80deede74d35c03cd90c57af5a0e897afa9ca49a460966e4e1cf0914325d/hostname",
        "HostsPath": "/var/lib/docker/containers/4f3a80deede74d35c03cd90c57af5a0e897afa9ca49a460966e4e1cf0914325d/hosts",
        "LogPath": "/var/lib/docker/containers/4f3a80deede74d35c03cd90c57af5a0e897afa9ca49a460966e4e1cf0914325d/4f3a80deede74d35c03cd90c57af5a0e897afa9ca49a460966e4e1cf0914325d-json.log",
        "Name": "/kafkadocker_kafka_1",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/var/run/docker.sock:/var/run/docker.sock:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "9092/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": ""
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Links": [
                "/kafkadocker_zookeeper_1:/kafkadocker_kafka_1/kafkadocker_zookeeper_1",
                "/kafkadocker_zookeeper_1:/kafkadocker_kafka_1/zk",
                "/kafkadocker_zookeeper_1:/kafkadocker_kafka_1/zookeeper_1"
            ],
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "ShmSize": 67108864,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "KernelMemory": 0,
            "Memory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Source": "/var/run/docker.sock",
                "Destination": "/var/run/docker.sock",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Name": "a9d7a91ffc59451190f0a15e3a50e93693f5bc36161d4f56bcd7e75b22d5f469",
                "Source": "/var/lib/docker/volumes/a9d7a91ffc59451190f0a15e3a50e93693f5bc36161d4f56bcd7e75b22d5f469/_data",
                "Destination": "/kafka",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "4f3a80deede7",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "9092/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "KAFKA_ADVERTISED_HOST_NAME=10.35.25.95",  <<<<<<<<<<<<<<<<<<
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/jdk/bin",
                "JAVA_VERSION_MAJOR=8",
                "JAVA_VERSION_MINOR=74",
                "JAVA_VERSION_BUILD=02",
                "JAVA_PACKAGE=server-jre",
                "JAVA_HOME=/opt/jdk",
                "LANG=C.UTF-8",
                "KAFKA_VERSION=0.9.0.1",
                "SCALA_VERSION=2.11",
                "KAFKA_HOME=/opt/kafka_2.11-0.9.0.1"
            ],
            "Cmd": [
                "start-kafka.sh"
            ],
            "Image": "kafkadocker_kafka",
            "Volumes": {
                "/kafka": {},
                "/var/run/docker.sock": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "161ca9990a314862c646d3175cf259074f40fcf5c5541c135fe04fa399ee5757",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "kafkadocker",
                "com.docker.compose.service": "kafka",
                "com.docker.compose.version": "1.6.2"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "aef30404ddf46fffbdf2592b784b374f4b807f396d3752c20385899d36f28f85",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "9092/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "32771"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/aef30404ddf4",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "48cdf54fe71e36755825e992ba8810c70723dbb110df975bfa99de4b75b4a431",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.4",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "right!",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "8a9edfb5ac87fb31a1bfdf466a99dc69d54d34e800da1c1a4e47480d9b81f0f2",
                    "EndpointID": "48cdf54fe71e36755825e992ba8810c70723dbb110df975bfa99de4b75b4a431",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.4",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "right!"
                }
            }
        }
    }
]

```

**Comment by asnir** [comment]
Hi @krishna81m, are sure that you are using the right port? 
Please execute this command: `docker-compose ps`  and share the output.

**Comment by krishna81m** [comment]
Think I did verify the ports already, did you see the zookeper exception? not sure if it is firewall related:
docker-compose ps
         Name                        Command               State                          Ports
----------------------------------------------------------------------------------------------------------------------
kafkadocker_kafka_1       start-kafka.sh                   Up      0.0.0.0:32771->9092/tcp
kafkadocker_zookeeper_1   /bin/sh -c /usr/sbin/sshd  ...   Up      0.0.0.0:32772->2181/tcp, 22/tcp, 2888/tcp, 3888/tcp

**Comment by asnir** [comment]
Please try this one.
`./start-kafka-shell.sh 10.35.25.95 10.35.25.95:32772`
instead of
`./start-kafka-shell.sh 10.35.25.95 10.35.25.95:2181`

**Comment by krishna81m** [comment]
Tried again with 32773 instead of the mapped/forwarded port 2181 and it worked :+1: :, let me see if I can access these from the outside though, because that was the purpose :).

```
./start-kafka-shell.sh ....              :32773
bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --create --topic test-topic --partitions 10 --zookeeper $ZK --replication-factor 2
Error while executing topic command : replication factor: 2 larger than available brokers: 1
[2016-03-11 20:14:53,156] ERROR kafka.admin.AdminOperationException: replication factor: 2 larger than available brokers: 1
        at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:77)
        at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:236)
        at kafka.admin.TopicCommand$.createTopic(TopicCommand.scala:105)
        at kafka.admin.TopicCommand$.main(TopicCommand.scala:60)
        at kafka.admin.TopicCommand.main(TopicCommand.scala)
 (kafka.admin.TopicCommand$)
bash-4.3# $KAFKA_HOME/bin/kafka-topics.sh --create --topic test-topic --partitions 10 --zookeeper $ZK --replication-factor 1
Created topic "test-topic".

docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
b7f209fcd960        tomcat                   "catalina.sh run"        2 seconds ago       Up 1 seconds        0.0.0.0:8080->8080/tcp                                sleepy_gates
1935c6e5c296        kafkadocker_kafka        "start-kafka.sh"         5 minutes ago       Up 5 minutes        0.0.0.0:32774->9092/tcp                               kafkadocker_kafka_1
16c2bdab3cd4        wurstmeister/zookeeper   "/bin/sh -c '/usr/sbi"   5 minutes ago       Up 5 minutes        22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:32773->2181/tcp   kafkadocker_zookeeper_1

zookeepr container logs:
2016-03-11 20:03:00,466 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1536746626b0000 type:delete cxid:0x31 zxid:0x15 txntype:-1 reqpath:n/a Error Path:/admin/preferred_replica_election Error:KeeperErrorCode = NoNode for /admin/preferred_replica_election
2016-03-11 20:03:00,558 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1536746626b0000 type:create cxid:0x38 zxid:0x16 txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NodeExists for /brokers
2016-03-11 20:03:00,558 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1536746626b0000 type:create cxid:0x39 zxid:0x17 txntype:-1 reqpath:n/a Error Path:/brokers/ids Error:KeeperErrorCode = NodeExists for /brokers/ids

```

And after topic creation, ZK logs, not sure what these ErrorCod's' are:

```
 NoNode for /brokers/topics/test-topic/partitions/5
2016-03-11 20:15:10,361 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1536746626b0000 type:create cxid:0x64 zxid:0x38 txntype:-1 reqpath:n/a Error Path:/brokers/topics/test-topic/partitions/2 Error:KeeperErrorCode = NoNode for /brokers/topics/test-topic/partitions/2
2016-03-11 20:15:10,371 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1536746626b0000 type:create cxid:0x67 zxid:0x3b txntype:-1 reqpath:n/a Error Path:/brokers/topics/test-topic/partitions/3 Error:KeeperErrorCode = NoNode for /brokers/topics/test-topic/partitions/3
2016-03-11 20:15:10,377 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x1536746626b0000 type:create cxid:0x6a zxid:0x3e txntype:-1 reqpath:n/a Error Path:/brokers/topics/test-topic/partitions/7 Error:KeeperErrorCode = NoNode for /brokers/topics/test-topic/partitions/7
```

**Comment by krishna81m** [comment]
Strangely, tomcat port forwarding looks correct and is accessible outside docker host but not Kafka/ZK. See for yourself:

```
># docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
ed1484d67c3c        wurstmeister/kafka       "/bin/bash"              8 minutes ago       Up 8 minutes                                                              elegant_saha
b7f209fcd960        tomcat                   "catalina.sh run"        40 minutes ago      Up 40 minutes       0.0.0.0:8080->8080/tcp                                sleepy_gates
1935c6e5c296        kafkadocker_kafka        "start-kafka.sh"         45 minutes ago      Up 45 minutes       0.0.0.0:32774->9092/tcp                               kafkadocker_kafka_1
16c2bdab3cd4        wurstmeister/zookeeper   "/bin/sh -c '/usr/sbi"   45 minutes ago      Up 45 minutes       22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:32773->2181/tcp   kafkadocker_zookeeper_1
># netstat -atun | grep 3277
tcp6       0      0 :::32773                :::*                    LISTEN  
tcp6       0      0 :::32774                :::*                    LISTEN  
tcp6       0      0 10.35.25.95:32773       172.17.0.7:46096        ESTABLISHED
tcp6       0      0 10.35.25.95:32774       172.17.0.6:59577        ESTABLISHED
tcp6       0      0 10.35.25.95:32774       172.17.0.7:56772        ESTABLISHED
tcp6       0      0 10.35.25.95:32773       172.17.0.7:46094        ESTABLISHED
tcp6       0      0 10.35.25.95:32774       172.17.0.6:59579        ESTABLISHED
># netstat -atun | grep 2181
tcp        0      0 172.17.0.1:44461        172.17.0.2:2181         ESTABLISHED
tcp        0      0 172.17.0.1:44459        172.17.0.2:2181         ESTABLISHED
># netstat -atun | grep 9092
tcp        0      0 172.17.0.1:59443        172.17.0.3:9092         ESTABLISHED
tcp        0      0 172.17.0.1:59439        172.17.0.3:9092         ESTABLISHED
tcp        0      0 172.17.0.1:59441        172.17.0.3:9092         ESTABLISHED
># netstat -atun | grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN 


```

**Comment by VatslavDS** [comment]
Hi everyone

In conclusion, What is the KAFKA_ADVERTISED_HOST_NAME for mac os x?
The problem occurs when in OSX there is no docker-machine by default.

Thank you.

**Comment by wurstmeister** [comment]
If you want to connect from different components within your compose file only, you can follow this example (irrespective of whether you are running docker-machine or docker natively):

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  consumer:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: [ "sh", "-c", "sleep 10 && $$KAFKA_HOME/bin/kafka-console-consumer.sh --topic=test --zookeeper=zookeeper:2181" ]
  producer:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: [ "sh", "-c", "sleep 15 && echo 'hello kafka' | $$KAFKA_HOME/bin/kafka-console-producer.sh --topic=test --broker-list=kafka:9092" ]
```

if you want to be able to connect from external components and run docker natively, you can set ```KAFKA_ADVERTISED_HOST_NAME``` to the IP of your host (e.g. the output of ```ifconfig en0```) if ```en0``` is your main interface.

i.e. if your IP address is 192.168.0.19


```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.0.19"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  consumer:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: [ "sh", "-c", "sleep 10 && $$KAFKA_HOME/bin/kafka-console-consumer.sh --topic=test --zookeeper=zookeeper:2181" ]
  producer:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: [ "sh", "-c", "sleep 15 && echo 'hello kafka' | $$KAFKA_HOME/bin/kafka-console-producer.sh --topic=test --broker-list=192.168.0.19:9092" ]
```

if you want to be able to connect from external components and run docker in docker-machine, you can set ```KAFKA_ADVERTISED_HOST_NAME``` to the IP of your docker-machine (e.g. the output of ```docker-machine ip local```) if ```local``` is your docker-machine name.

i.e. if your docker-machine IP address is 192.168.99.100

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.99.100"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  consumer:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: [ "sh", "-c", "sleep 10 && $$KAFKA_HOME/bin/kafka-console-consumer.sh --topic=test --zookeeper=zookeeper:2181" ]
  producer:
    image: wurstmeister/kafka
    depends_on:
      - kafka
    command: [ "sh", "-c", "sleep 15 && echo 'hello kafka' | $$KAFKA_HOME/bin/kafka-console-producer.sh --topic=test --broker-list=192.168.99.100:9092" ]
```

**Comment by chenziliang** [comment]
@wurstmeister In MacOS, it seems I still can't make it work. All my services are running in docker natively on MacOS (without docker-machine). All services share the same docker network, and i can ping each service name from the running docker container. I don't need expose kafka broker for external use. So I expect the following config should work, but it doesn't. For consumer in myapp, it reported **"error": "kafka server: Offset's topic has not yet been created."**; for producer in myapp, it reported **"error": "circuit breaker is open"**. 

Any idea is highly appreciated !

{code}
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  myapp: # which tries to kafka through "kafka:9092"
    build: .
    depends_on:
      - kafka
    command: ...

{code}

**Comment by chenziliang** [comment]
BTW, KAFKA_ADVERTISED_HOST_NAME is already deprecated in 0.10+ kafka. I also tried **KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://10.0.0.75:9092"** etc, still no luck

**Comment by BBartosz** [comment]
@chenziliang how do you connect to this kafka from myapp? It should be "broker.servers = kafka:9092"

**Comment by steverhoades** [comment]
@chenziliang did you ever get this to work?  I cannot seem to get this working either with a similar configuration.

**Comment by chenziliang** [comment]
No

**Comment by raofq** [comment]
@chenziliang is ok now ?  KAFKA_ADVERTISED_HOST_NAME: "kafka"  => KAFKA_ADVERTISED_HOST_NAME: kafka. try it.

**Comment by chandradeepak** [comment]
I encountered similar issue ,  this issue might happens in the following scenario. For some reason if the connectivity between client and zookeeper is fine and you create the topic , then later you fixed the connectivity from client to kafka is fixed , now if you ingest data for the topic you created before it might think since the topic is created there is no need to create a topic and kafka will never create the topic in the  kafka logs where it stores data and you might get exceptions for ingesting data.  Try with a different topic it should work . 

This is my version of docker file . 

version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:0.10.2.1
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
          - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

**Comment by YonatanKiron** [comment]
Hi, I might solved this:
```
version: '3.4'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD", "/opt/zookeeper/zkServer.sh", "status"]
      interval: 5s
      timeout: 5s
      retries: 3
    volumes:
      - ./data/zookeeper:/opt/zookeeper/data
  kafka:
    image: wurstmeister/kafka:0.10.0.0
    ports:
      - 9092:9092
    environment:
      KAFKA_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKERHOST}"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${DOCKERHOST}:9092"
      KAFKA_ZOOKEEPER_CONNECT: "${DOCKERHOST}:2181"
      KAFKA_LOG_DIRS: /kafka/logs
    depends_on:
      - zookeeper
    volumes:
      - ./data/kafka/:/kafka/
    extra_hosts:
      - "dockerhost:$DOCKERHOST"
```
While DOCKERHOST is:
`DOCKERHOST=$(ifconfig | grep -E "([0-9]{1,3}\.){3}[0-9]{1,3}" | grep -v 127.0.0.1 | awk '{ print $2 }' | cut -f2 -d: | head -n1)`
