### ISSUE TITLE
Invalid value  for configuration advertised.port: Not a number of type INT

### ISSUE THREAD

**Issue by titoc** [wurstmeister/kafka-docker#170]
Hello all, 

I just cloned the repo and modified KAFKA_ADVERTISED_HOST_NAME to my host ip and did docker-compose up and it came up with the below error. I know there is another [issue filed ](https://github.com/wurstmeister/kafka-docker/issues/111) and a [PR made to fix it](https://github.com/wurstmeister/kafka-docker/pull/82/files), but none of the proposed solutions worked.

```
Docker version: 1.10.3
Kernel Version: 3.10.0-327.28.2.el7.x86_64
```

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.34.203
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

```
zookeeper_1  | 2017-02-16 17:18:22,737 [myid:] - INFO  [main:NIOServerCnxnFactory@89] - binding to port 0.0.0.0/0.0.0.0:2181
kafka_1      | [2017-02-16 17:18:24,783] FATAL  (kafka.Kafka$)
kafka_1      | org.apache.kafka.common.config.ConfigException: Invalid value  for configuration advertised.port: Not a number of type INT
kafka_1      |  at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:669)
kafka_1      |  at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:418)
kafka_1      |  at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
kafka_1      |  at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:794)
kafka_1      |  at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:778)
kafka_1      |  at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:775)
kafka_1      |  at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1      |  at kafka.Kafka$.main(Kafka.scala:58)
kafka_1      |  at kafka.Kafka.main(Kafka.scala)
kafkadocker_kafka_1 exited with code 1
```

**Comment by ponima520** [comment]
i already slove the problem. From the problem, you can see the "advertised.port" tha mean you must set this  and can not null.
So we can 
    environment:
       KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
       KAFKA_CREATE_TOPICS: "test:1:1"
       KAFKA_ADVERTISED_PORT: 9092
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
       KAFKA_LISTENERS: PLAINTEXT://:9092
       TZ: CST-8
Un, you can see the third line and its port is not null.

**Comment by worktchaloemphon** [comment]
> i already slove the problem. From the problem, you can see the "advertised.port" tha mean you must set this and can not null. So we can environment: KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 KAFKA_CREATE_TOPICS: "test:1:1" KAFKA_ADVERTISED_PORT: 9092 KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092 KAFKA_LISTENERS: PLAINTEXT://:9092 TZ: CST-8 Un, you can see the third line and its port is not null.


Thank bro it work!!!

And my edited docker-compose is

``` yaml
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    build: .
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092 <-------------- Add this line
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

```
