### ISSUE TITLE
When JMX_PORT specified, cannot use kafka-console-producer/consumer

### ISSUE THREAD

**Issue by jaksky** [wurstmeister/kafka-docker#171]
When I try to enable JMX for kafka single broker, I cannot used internal kafka CLI client.

Adding JMX_PORT=9999 and/or KAFKA_JMX_OPTS to docker compose when I exec to docker container I cannot run 
bash-4.3# ./kafka-console-producer.sh --broker-list kafka:9092 --topic test
Error: JMX connector server communication error: service:jmx:rmi://kafka:9999
bash-4.3# ping kafka
PING kafka (172.19.0.3): 56 data bytes
64 bytes from 172.19.0.3: seq=0 ttl=64 time=0.099 ms

Tried to fiddle with KAFKA_ADVERTISED_HOST_NAME and with -Djava.rmi.server.hostname=kafka but with no luck.

My exact config:
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.10.1.1
    container_name: kafka
    hostname: kafka
    build: .
    links:
      - zookeeper:zookeeper
    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=
      - KAFKA_ADVERTISED_PORT=9092
      - BROKER_ID=1
      - ZK_HOSTS=zookeeper:2181
      - AUTO_CREATE_TOPICS=true
      - DEFAULT_REPLICATION_FACTOR=1
      - NUM_PARTITIONS=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - JMX_PORT=9999
      - KAFKA_JMX_OPTS= -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9999
    ports:
      - "9092:9092"
      - "9999:9999"

**Comment by jaksky** [comment]
Same variables are used when running client so they are in clash. Erase JMX_PORT before client run works

**Comment by ray1888** [comment]
@jaksky how do u slove this problem? i met the same problem as u do.but i need jmx port export for monitoring reason.so how can i create topic and open the jmx port at the same time.if u have fix it ,can u explain how to do that? thx

**Comment by jaksky** [comment]
It is some time ago, but I was solving that if I remember correctly by exporting JMX_PORT variable again after login to container

**Comment by anshitabharti** [comment]
@ray1888 did you find any solution for this ?

**Comment by elaijuh** [comment]
Just `unset JMX_PORT` after you login container

**Comment by megastef** [comment]
I use following docker-compose settings: 

```
kafka:
    image: wurstmeister/kafka:0.9.0.1
    depends_on: 
      - zookeeper
    ports:
      - 9092:9092
    links:
      - zookeeper
    labels:
        - SPM_TOKEN=${SPM_TOKEN}
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote.port=3000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false
```

And see an exception from Kafka:
```
kafka_1       | [2017-10-04 22:40:18,298] INFO New leader is 1004 (kafka.server.ZookeeperLeaderElector$LeaderChangeListener)
kafka_1       | creating topics: test:1:1
kafka_1       | Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 3000; nested exception is: 
kafka_1       | 	java.net.BindException: Address already in use
```

How can I enable JMX?
