### ISSUE TITLE
unable to launch kafka-cluster on local minikube

### ISSUE THREAD

**Issue by lechen26** [wurstmeister/kafka-docker#189]
Hi

i'm unable to launch a kafka cluster on a local minikube installation, using NodePort.
i saw a lot of comments on the net, but was unable to solve that properly.

here is my latest yml file that i've used.

```
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: zookeeper-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
      name: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
        name: zookeeper-1
    spec:
      containers:
      - name: zoo1
        image: digitalwonderland/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
---
apiVersion: v1
kind: Service
metadata:
  name: zoo1
  labels:
    app: zookeeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper-1
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "192.168.99.100"
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:1:1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
   app: kafka
spec:
  ports:
  - name: client
    port: 31069
    protocol: TCP
    targetPort: 9092
    nodePort: 31069
  type: NodePort
  selector:
   app: kafka
```

after everything is running, i can access my minikube ip: 31069 but when trying to produce/consume message using kafkacat nothing happens.
tried also using advertized_host based on the pod ip, didnt helped.

any help will be appriciated.

thanks!
~
