### ISSUE TITLE
Docker-image is not working on OS-X

### ISSUE THREAD

**Issue by allquantor** [wurstmeister/kafka-docker#192]
Kafka can not receive published messages.

Reproducable:
- Set ADVERTISED_HOPST_NAME to `127.0.0.1`
- Start with: `docker-compose -f docker-compose-single-broker.yml up`
- Start publishing `kafkacat -P -b 127.0.0.1:9092 -t test`
- Start subscribing `kafkacat -C -b 127.0.0.1:9092 -t test`

No response. When you kill the docker machine the connection on consumer breaks
```
% ERROR: Local: Broker transport failure: 127.0.0.1:9092/1002: Receive failed: Disconnected
% ERROR: Local: All broker connections are down: 1/1 brokers are down : terminating
```

Same with if producing/consuming messages with `reactive-kafka` in `Scala`.

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by sscaling** [comment]
Following your steps to reproduce, I have no problem interacting with the broker via `kafkacat`.

docker-compose.yml
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

versions:
```
$ docker version
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true
```
Have you checked the kafka and zookeeper logs to make sure they have started correctly? Are there any errors? Do you have a firewall running on your machine, is that blocking connections?
