### ISSUE TITLE
Allow multiline definition of KAFKA_CREATE_TOPICS

### ISSUE THREAD

**Issue by stphngrtz** [wurstmeister/kafka-docker#208]
Hi! It would be nice to be able to specify the topics to be created on startup with newlines.

```yaml
    ...
      KAFKA_CREATE_TOPICS: |
        topic1:100:3
        topic2:100:3
        topic3:100:3
        ...
```
docker-compose.yml

**Comment by aleksandr-vin** [comment]
One can use this workaround:

```
    environment:
       KAFKA_CREATE_TOPICS:
         "topic1:100:3\
          topic2:100:3\
          topic3:100:3"
```

**Comment by grigorovich-czi** [comment]
There is an issue with that. On first run it works well. But if you stop container and then run it again, it will fail with such error
```
kafka_1            | Excluding KAFKA_HOME from broker config
kafka_1            | waiting for kafka to be ready
kafka_1            | [Configuring] 'port' in '/opt/kafka/config/server.properties'
kafka_1            | [Configuring] 'create.topics.separator' in '/opt/kafka/config/server.properties'
kafka_1            | sed: unmatched '@
```
server.properties at that moment looks like
```
...
create.topics.separator=$'
'
```
Not sure, but this single quote on next line probably breaks something.

**Comment by gustavosoares** [comment]
Having the same issue as reported above

```
Starting dev_kafka_1 ... done
Attaching to dev_kafka_1
kafka_1      | Excluding KAFKA_HOME from broker config
kafka_1      | waiting for kafka to be ready
kafka_1      | [Configuring] 'advertised.host.name' in '/opt/kafka/config/server.properties'
kafka_1      | [Configuring] 'port' in '/opt/kafka/config/server.properties'
kafka_1      | [Configuring] 'create.topics.separator' in '/opt/kafka/config/server.properties'
kafka_1      | sed: unmatched '@'
dev_kafka_1 exited with code 1
```

**Comment by tvhung83** [comment]
+1 same issue with `docker-compose` config:
```yaml
    environment:
      KAFKA_ADVERTISED_HOST_NAME: broker
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS_SEPARATOR: "$$'\n'"
      KAFKA_CREATE_TOPICS: |
        topic_1:1:1
        topic_2:1:1
```
