### ISSUE TITLE
WARN Connection to node 1001 could not be established. Broker may not be available.

### ISSUE THREAD

**Issue by SquirrelNinja** [wurstmeister/kafka-docker#211]
Running this on Mac Sierra

Started this up using this config:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "lambda1:1:1"
    volumes:
      - /Users/<user>/projects/aa_dev_kafka/docker.sock:/var/run/docker.sock
```

Everything appears to start up, however the log kafka log is full of these errors:

WARN Connection to node 1001 could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

I saw a couple of post indicating it might be a firewall issue, however I am not running a FW locally

**Comment by SquirrelNinja** [comment]
I deleted the images, the local mapping, and set the docker-compose.yml file to it's stock setting and I am still getting the error.

**Comment by agolomoodysaada** [comment]
I'm also experiencing this issue with
```yml
version: '3.3'
services:
  kafka:
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - 9092:9092
    network_mode: host
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      LOG4J_LOGGER_KAFKA_AUTHORIZER_LOGGER: DEBUG, authorizerAppender
  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    network_mode: host
    environment:
      ZOO_MY_ID: 1
```
