### ISSUE TITLE
KAFKA_ADVERTISED_HOST_NAME

### ISSUE THREAD

**Issue by cmreigrut** [wurstmeister/kafka-docker#233]
According to the docs, setting KAFKA_ADVERTISED_HOST_NAME in the environment section should change the advertised host, right?  It doesn't appear to work...

```
docker-compose.yml
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 10.17.230.67
      KAFKA_CREATE_TOPICS: "test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

log from docker-compose up
```
kafka_1      | [2017-11-15 00:14:49,290] INFO KafkaConfig values:
kafka_1      |  advertised.host.name = null
kafka_1      |  advertised.listeners = PLAINTEXT://10.17.230.67:9092
kafka_1      |  advertised.port = null
kafka_1      |  alter.config.policy.class.name = null
kafka_1      |  authorizer.class.name =
kafka_1      |  auto.create.topics.enable = true
```
