### ISSUE TITLE
Remove deprecated configuration settings

### ISSUE THREAD

**Issue by matthewadams** [wurstmeister/kafka-docker#244]
The latest image uses (and refers to in documentation) deprecated configuration settings.

Please update the image and documentation to use only undeprecated configuration settings as of Kafka 1.0.0.

**Comment by bryanleekw** [comment]
Thanks... may I know any kafka classes depreciated? or we simply download version 1.0.0 and then build the image

**Comment by matthewadams** [comment]
I didn't mention any *classes* per se.  I only noticed that there are configuration *settings* that you use that are now deprecated.  See https://kafka.apache.org/documentation/#configuration.  The `DESCRIPTION` column has many configuration settings that begin with `DEPRECATED`.

**Comment by bryanleekw** [comment]
ic... Many thanks. Let's me rebuild it with version 1.0.0 with my own program.

**Comment by matthewadams** [comment]
@bryanleekw Make sure you're using *zero* deprecated settings...

**Comment by MartinX3** [comment]
Please remove the deprecated settings.
We get weird errors, because we arn't using any deprecated setting, which is needed by your outdated image.

**Comment by sscaling** [comment]
@MartinX3 - Please can you be more specific? Which specific settings are you having issues with? What version of the image are you using? What are the 'weird errors' you are getting etc? What is your configuration?

**Comment by MartinX3** [comment]
@sscaling

The advertised host Name is deprecated 
The advertised listener shloud be used now

I need to set the deprecated variable to set both 
That's weird

the advertised host name shouldn't be used anymore

**Comment by sscaling** [comment]
@MartinX3 - You should be able to configure both of these via the normal `KAFKA_XXX` environment vars. There is a current PR open to remove some of the prescriptive/invasive configuration settings (https://github.com/wurstmeister/kafka-docker/pull/286) which may be leading to some strange behaviour. i.e. it will automatically try to configure the newer `advertised.listeners` property [https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L62](https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L62)

It would be useful to see your docker-compose file (or configured environment vars) and the contents of the `/opt/kafka/config/server.properties` file (output in the kafka container startup logs) to see what your input config and output state is.

**Comment by MartinX3** [comment]
@sscaling 
Maybe I should wait until the PR #286 hast been merged and test it again. :)

**Comment by matthewadams** [comment]
Regardless of the outcome of #286, the image and its documentation should
be updated to reflect the current configuration settings, including
indicated which settings/environment variables are now deprecated.

**Comment by sscaling** [comment]
@matthewadams - the image does not aim to be opinionated. If the user chooses to set the deprecated settings that is the end-user choice. PR #286 should allow this - and is more importantly a step to being able to back-port master to release branches. 

The documentation references deprecated settings as it still applies to older version of Kafka (that are still supported). The deprecated settings currently work across all branches.

As an aside - the current codebase should generally only set the new (non-deprecated) config. I'm still waiting for someone to provide a concrete case for a broken config so we can fix/test any specific error cases.

**Comment by sscaling** [comment]
@MartinX3 - #286 is merged. Please could you check to see if that resolves your issues?

**Comment by MartinX3** [comment]
@sscaling Thank you, but it doesn't helped me. :(
The deprecated host name still needs to be set.
Set only the listener doesn't works.

**Comment by MartinX3** [comment]
We don't use docker compose, but her are our yaml files

kafka.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-prod
  labels:
    app: kafka-prod
spec:
  ports:
  - name: kafka-prod
    port: 9092
    protocol: TCP
  selector:
    app: kafka-prod
  externalIPs:
  - 192.168.2.146 #angola
  - 192.168.2.145 #congo
  - 192.168.2.113 #korea
  - 192.168.2.125 #romania
  - 192.168.2.116 #macedonia
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-prod
      name: kafka-prod
  template:
    metadata:
      labels:
        app: kafka-prod
        name: kafka-prod
    spec:
      containers:
      - name: kafka-prod
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        # wird gebraucht fuers wurstmeister image
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-prod"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-prod:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "courses-kafka-zookeeper.default.svc.cluster.local"
```

zookeeper.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: courses-kafka-zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: zookeeper
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
      name: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
        name: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER
          value: courses-kafka-zookeeper
```

**Comment by sscaling** [comment]
@MartinX3 - you may have issues because you specify both advertised.port and advertised.host.name. They are both replaced by advertised.listeners.

You should only need these settings, which work without error in the current image:

```
env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-prod:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "courses-kafka-zookeeper.default.svc.cluster.local"
```

This can be seen in some of the tests, such as https://github.com/wurstmeister/kafka-docker/blob/master/test/test.start-kafka-port-command.kafka.sh
