### ISSUE TITLE
Accessing Kafka monitoring parameters via JMX

### ISSUE THREAD

**Issue by asha47** [wurstmeister/kafka-docker#252]
Hi

I am trying to create a monitoring mechanism for Kafka and trying to enable JMX configuration through Java code. Below is the snippet of the code - 

withEnv("KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://" + DockerSupport.lookupContainerHost(DOCKER_CLIENT)
                                + ":" + port,
                        "KAFKA_LISTENERS=PLAINTEXT://:9092",
                        "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181",
                        "KAFKA_ADVERTISED_HOST_NAME=localhost",
                        "KAFKA_CREATE_TOPICS=Topic1:1:1",
                        "JMX_PORT=9997",                        
                        "KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9997"
                		)

Now the Kafka is running fine, but I am not able to get any JMX info on the url 127.0.0.1:9997. Please advise a way to resolve this.

Thanks
Avinash

**Comment by sscaling** [comment]
Have you published the JMX port (9997)?

The below `docker-compose.yml` works fine for me, with latest on mac with Docker for Mac 17.12.0 CE
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "9997:9997"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9997
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

specifically pay attention to the 

```
ports:
   - "9997:9997"
```

You should then be able to validate connection with `jconsole` from the command line, such as

```
jconsole localhost:9997
```
