### ISSUE TITLE
Docker for mac - Can't produce outside container

### ISSUE THREAD

**Issue by jmcarvalho** [wurstmeister/kafka-docker#255]
Hi. 
As I am running docker natively I used the _**docker.for.mac.localhost**_  as KAFKA_ADVERTISED_ HOST_NAME
Producing and consuming inside the container is working ok, however when I try to produce events outside the container setting **("bootstrap.servers", "localhost:9092")** I get a timeout exception probably due to the fact that the producer can't reach the cluster.
Is there any solution for that? 

docker- compose:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logs_topic:1:1"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    container_name: kafka
```
