### ISSUE TITLE
Configuring log.retention.ms seems broken(?) on 0.9.0.1 tag

### ISSUE THREAD

**Issue by srijeet0406** [wurstmeister/kafka-docker#260]
Hi,
I'm trying to set the topic retention time on my topics using the KAFKA_LOG_RETENTION_MS field inside my kubernetes replication controller file, but it doesn't seem to take effect when I describe the topics. I also tried to put the value in the docker-compose.yml file, but that didnt help either. I have tried various permutations and combinations of this, but with no luck. Any help appreciated!!

Here is my docker-compose.yml file:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "Topic7:1:1"
      KAFKA_LOG_RETENTION_MS: 1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
