### ISSUE TITLE
How to persist data when used with Docker Swarm ?

### ISSUE THREAD

**Issue by ikus060** [wurstmeister/kafka-docker#263]
Mostly a question how to get this setup working.
I want to start Kafka on docker swarm. When I reboot the service, I don't want to lost any data. Reading previous, I've already create a volume for `/kafka`. The issue I have right now is the broker id. I understand it need to be static for each instance.
How can I make it static when using `deploy: mode: global` ??
Here is my docker-compose:
```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      JMX_PORT: 9010
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9010"
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/kafka:/kafka
    deploy:
      mode: global

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
    - target: 9000
      published: 9090
      protocol: tcp
      mode: ingress
    environment:
      KM_CONFIG: /srv/kafka-manager/custom.conf
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: letmein
      #KAFKA_MANAGER_AUTH_ENABLED: 'true'
      #KAFKA_MANAGER_USERNAME: admin
      #KAFKA_MANAGER_PASSWORD: password
    volumes:
      - /srv/kafka-manager:/srv/kafka-manager
    deploy:
      placement:
        constraints:
        - node.role==manager
```

**Comment by saule1508** [comment]
Same question here. I guess we have to use BROKER_ID_COMMAND, in the doc there is an example:
 
BROKER_ID_COMMAND: "hostname | awk -F'-' '{print $2}'"

However the broker_id must be an integer (starting with 0 and incrementing...) so we need a command that generates such an integer...

**Comment by jordijansen** [comment]
Yeah I got the same issue. My current workaround is have 3 service definitions (kafka1, kafka2, kafka3) with static config for the KAFA_BROKER_ID and placement on the node using:
```
      placement:
        constraints:
        - node.labels.sector == messaging
        - node.hostname == EVT01
```

**Comment by saule1508** [comment]
It makes sense, I think it is the way to go and besides I did not like to use deploy: mode: global (it is overkill)

Something else that puzzle me. In the start-kafka.sh there is this piece of code that generate a new logs directory every time the container is started (because its host changed)

```
if [[ -z "$KAFKA_LOG_DIRS" ]]; then
    export KAFKA_LOG_DIRS="/kafka/kafka-logs-$HOSTNAME"
fi
```

so in the docker-compose we must add the env KAFKA_LOG_DIRS I believe

```
    environment:
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/kafka:/kafka
```

**Comment by raarts** [comment]
Here is my swarm stack setup:

```
version: "3.2"

services:
  zoo1:
    image: zookeeper
    volumes:
      - zookeeper_conf:/conf
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - zookeeper
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      placement:
        constraints:
          - node.labels.zookeeper == 1
      replicas: 1
      restart_policy:
        delay: 2s
        window: 20s

  zoo2:
    image: zookeeper
    volumes:
      - zookeeper_conf:/conf
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - zookeeper
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    deploy:
      placement:
        constraints:
          - node.labels.zookeeper == 2
      replicas: 1
      restart_policy:
        delay: 2s
        window: 20s

  zoo3:
    image: zookeeper
    volumes:
      - zookeeper_conf:/conf
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - zookeeper
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    deploy:
      placement:
        constraints:
          - node.labels.zookeeper == 3
      replicas: 1
      restart_policy:
        delay: 2s
        window: 20s

  kafka:
    image:  wurstmeister/kafka:latest
    ports:
      - target: ${KAFKA_PORT}
        published: ${KAFKA_PORT}
        protocol: tcp
        mode: host
    networks:
      - zookeeper
      - kafka
    volumes:
      - kafka_data:/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: "{{.Node.Hostname}}"
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: ${KAFKA_PORT}
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9094
      KAFKA_LOG_DIRS: /kafka/logs
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.kafka == True
      restart_policy:
        delay: 2s
        window: 20s

# local-persist driver only works with swarm if it finds at least one volume at startup
volumes:
  zookeeper_conf:
    driver: local-persist
    driver_opts:
      mountpoint: /data/${ENV}/${CI_PROJECT_PATH_SLUG}/zookeeper/conf
  zookeeper_data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/${ENV}/${CI_PROJECT_PATH_SLUG}/zookeeper/data
  zookeeper_datalog:
    driver: local-persist
    driver_opts:
      mountpoint: /data/${ENV}/${CI_PROJECT_PATH_SLUG}/zookeeper/datalog
  kafka_data:
    driver: local-persist
    driver_opts:
      mountpoint: /data/${ENV}/${CI_PROJECT_PATH_SLUG}/kafka/data

networks:
  zookeeper:
    driver: overlay
  kafka:
    driver: overlay
```

Basically I label a few nodes with `kafka: True`. I also use the local-persist volume driver on every node.
