### ISSUE TITLE
java.lang.NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by cevaris** [wurstmeister/kafka-docker#28]
Seems there may be some config issue.

Fig file
```
kafka:
  image: wurstmeister/kafka:latest
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.105
```
Error message
```
Status: Downloaded newer image for wurstmeister/kafka:latest
Attaching to gokafkaexample_kafka_1
kafka_1 | 2015/02/04 19:32:38 Get http:///var/run/docker.sock/v1.12/containers/225d9cec78c4/json: dial unix /var/run/docker.sock: no such file or directory
kafka_1 | [2015-02-04 19:32:39,399] FATAL  (kafka.Kafka$)
kafka_1 | java.lang.NumberFormatException: For input string: ""
kafka_1 |       at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
kafka_1 |       at java.lang.Integer.parseInt(Integer.java:493)
kafka_1 |       at java.lang.Integer.parseInt(Integer.java:514)
kafka_1 |       at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:207)
kafka_1 |       at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
kafka_1 |       at kafka.utils.VerifiableProperties.getIntInRange(VerifiableProperties.scala:73)
kafka_1 |       at kafka.utils.VerifiableProperties.getIntInRange(VerifiableProperties.scala:46)
kafka_1 |       at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:49)
kafka_1 |       at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:31)
kafka_1 |       at kafka.Kafka$.main(Kafka.scala:35)
kafka_1 |       at kafka.Kafka.main(Kafka.scala)
gokafkaexample_kafka_1 exited with code 0
Gracefully stopping... (press Ctrl+C again to force)
```

**Comment by wurstmeister** [comment]
please see https://github.com/wurstmeister/kafka-docker/issues/26

**Comment by wurstmeister** [comment]
Did you manage to solve the problem?

Thanks

**Comment by cevaris** [comment]
I have not tried since, so no.

On Fri, Feb 20, 2015 at 8:19 AM, wurstmeister <notifications@github.com>
wrote:

> Did you manage to solve the problem?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wurstmeister/kafka-docker/issues/28#issuecomment-75254436>
> .
>



-- 
Warm Regards,
Julian Cevaris

Blogspot <http://draft-new-religion.blogspot.com/> -  Google+
<https://plus.google.com/111474132801017393519/posts> - Facebook
<http://www.facebook.com/profile.php?id=100003308886461> - Twitter
<http://twitter.com/#!/cevaris>

**Comment by drob** [comment]
This issue was solved for me by manually mounting `/var/run/docker.sock` for the kafka containers. I.e., my fig.yml looks like this:
```yml
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181"

kafka:
  build: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092"
  links:
    - zookeeper
  environment:
    KAFKA_ZOOKEEPER_CONNECT: zookeeper
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```
Manually mounting this seems like a bit of a hack, as no other docker images I'm using require doing so. Is this intended behavior?

I only intend to run a single broker for now, so it shouldn't matter that I haven't set `KAFKA_ADVERTISED_HOST_NAME`. (Or am I misinterpreting the documentation?)
