### ISSUE TITLE
Issue with Kafka in swarm mode. 

### ISSUE THREAD

**Issue by mrafeeq** [wurstmeister/kafka-docker#288]
I used the below swarm docker-compose.yml

and then gave `docker compose up -d `  and then docker-compose scale kafka=2 I get error that port 9094 is already in assigned . sorry if this is a dumb question. my clients (producer) is a spring boot application  and uses spring kafka to connect  

If i do not give the internal hostname then, a random port like 30000  is assigned  what url should the kafka.bootstrap-servers use . i tried hostname:30000. Sometimes it gives error like brocker not found or LEADER_NOT_FOUND sometimes. 

but before going to issue 2, why does the scale command not run succesfully 

```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: ${REPO}kafka-docker:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.soc
```
