### ISSUE TITLE
SASL_PLAIN/SSL KAFKA_OPTS not being set

### ISSUE THREAD

**Issue by jduffy3** [wurstmeister/kafka-docker#312]
I'm trying to pass some variables into the KAFKA_OPTS var but 
I keep seeing this in the logs

/usr/bin/start-kafka.sh: line 96: KAFKA_OPTS=-Djava.security.auth.login.config: bad substitution

I'm trying to set the following variable
KAFKA_OPTS: "-Djava.security.auth.login.config=/kafka_server_jaas.conf"

Can you please explain why I can't set this? Or how I might go about doing it

**Comment by sscaling** [comment]
I believe his is part of a larger namespace collision problem that affects multiple elements such as Kubernetes deployments etc (as well as other KAFKA_ service settings).

Given you are referencing an external file `/kafka_server_jaas.conf`, i'm assuming you're OK adding/mounting extra files through; a work-around is to specify a `CUSTOM_INIT_SCRIPT` environment var, which should be a script similar to:

```
#!/bin/bash
export KAFKA_OPTS="-Djava.security.auth.login.config=/kafka_server_jaas.conf"
```

This is executed after the substitution part that is failing.

This could have been done inline, however there is currently a bug in how we process the environment, where we need to specify the input separator to make this work correctly.

**Comment by sscaling** [comment]
Have opened https://github.com/wurstmeister/kafka-docker/issues/313 to track the second issue I mentioned.

**Comment by jduffy3** [comment]
I tried the following but it hasn't corrected it. 
```
Is there something I'm missing?

  kafka:
    image: 'wurstmeister/kafka:latest'
    volumes:
      - "./env.sh:/usr/local/bin/env.sh"
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HOST_NAME: 10.10.10.1
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: 10.10.10.1
      KAFKA_LISTENERS: PLAINTEXT://:9092,SASL_SSL://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.10.1:9092,SASL_SSL://10.10.10.1:9093
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SSL_TRUSTSTORE_LOCATION: /kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
      KAFKA_SSL_KEYSTORE_LOCATION: /kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: password
      KAFKA_SSL_KEY_PASSWORD: password

    command:
      - env.sh
      - /usr/bin/start-kafka.sh
```

**Comment by sscaling** [comment]
look at https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L112

I think you should have something like

```
kafka:
    volumes:
      - "./env.sh:/usr/local/bin/env.sh"
    environment:
       CUSTOM_INIT_SCRIPT: "./env.sh"
```
