### ISSUE TITLE
"Refusing session request for client" when starting Zookeeper and Kafka from scratch 

### ISSUE THREAD

**Issue by rsetia** [wurstmeister/kafka-docker#315]
I am trying to follow the Wiki (https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) by setting up the most simple configuration using the following docker-compose that I derived from docker-compose-single-broker.yml in this repo:

```
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Before doing a "docker-compose up" I deleted all of my docker data. However, I see the following error: 

```
zookeeper_1  | 2018-04-11 21:18:56,722 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /172.18.0.1:42470
zookeeper_1  | 2018-04-11 21:18:56,725 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@901] - Refusing session request for client /172.18.0.1:42470 as it has seen zxid 0x134 our last zxid is 0x3b client must try another server
zookeeper_1  | 2018-04-11 21:18:56,725 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /172.18.0.1:42470 (no session established for client)
``` 

Any ideas? I am not sure how this can happen when I am starting from scratch.
