### ISSUE TITLE
KAFKA_CREATE_TOPICS gives TimeoutException

### ISSUE THREAD

**Issue by rorygilfillan** [wurstmeister/kafka-docker#327]
I'm getting TimeoutExceptions when I try to send messages to a topics that are created with KAFKA_CREATE_TOPICS. The following is my docker-compose file:

```
version: '2'
services:
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
        ports:
          - 2181:2181
    kafka:
        image: wurstmeister/kafka:1.1.0
        environment:
            KAFKA_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "test:1:1"
        ports:
            - 9092:9092
```

When I try to send a message to test with 
`.\kafka-console-producer.bat --broker-list kafka:9092 --topic test`

The result is 
`org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for test-0: 1530 ms has passed since batch creation plus linger time`

When I create the topic manually with
 `.\kafka-topics.bat --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test1`

and then send a message with 
`.\kafka-console-producer.bat --broker-list kafka:9092 --topic test1` 
It works fine.
