### ISSUE TITLE
Usage of docker image in minikube (Kubernetes)

### ISSUE THREAD

**Issue by dvirgiln** [wurstmeister/kafka-docker#329]
Hi,

I am trying to use your docker image with Kubernetes using minikube in my local machine.

https://github.com/dvirgiln/streams-kafka/blob/master/kubernetes/1_kafka_broker_wurstmeister.yml

I have tried different setups i found in internet, but no-one worked.

With the current one I receive an error in the consumer: {test=LEADER_NOT_AVAILABLE}

Could you tell me what should be the configuration?

**Comment by dvirgiln** [comment]
So, including some more information:

{code}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker-svc
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    nodePort: 30092
    targetPort: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 192.168.99.100:30181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://192.168.99.100:30092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
{code}

**Comment by dvirgiln** [comment]
If i try this other config:

So, including some more information. If I create the broker like this specifying
- name: KAFKA_ADVERTISED_LISTENERS
value: PLAINTEXT://192.168.99.100:30092
- name: KAFKA_LISTENERS
value: PLAINTEXT://0.0.0.0:30092

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker-svc
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    nodePort: 30092
    targetPort: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 192.168.99.100:30181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://192.168.99.100:30092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:30092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
```
Kafka initializes correctly, but then the producer send this error:

`[Producer clientId=producer-1] Connection to node -1 could not be established. Broker may not be available.`

I tried nc to check that the 30092 port is accessible:
nc -zv 192.168.99.100 30092
nc: connectx to 192.168.99.100 port 30092 (tcp) failed: Connection refused

So, for some reason when the kafka listener is set to point to the external 9092 port (30092), it then fails to access that port from outside...

**Comment by sscaling** [comment]
None of your attached config looks quite correct - have a look at https://github.com/wurstmeister/kafka-docker/wiki/Connectivity. One of the biggest challenges I think you'll have using `NodePort` is that the IP associated to that is internal to the K8s overlay network.

A quick play shows something like this might work:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-broker
  name: kafka-internal-svc
spec:
  ports:
  - port: 9092
  selector:
    app: kafka-broker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-broker
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.96.0.99:2181
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker:9092
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka-broker
        ports:
        - containerPort: 9092
```
**NOTE:** the `hostname` property of the deployment spec

If you want to access from outside the cluster, user `port-forward`, e.g.

```
kubectl port-forward <kafka pod name> 9092
```

You will then need to have your `/etc/hosts` configured to route the _kafka-broker_ hostname

```
127.0.0.1 kafka-broker
```

And finally connect to it such as:

```
$ echo "foo" | kafkacat -P -b kafka-broker:9092 -t test
$ kafkacat -C -b kafka-broker:9092 -t test
foo
% Reached end of topic test [0] at offset 1
```

Of course, this doesn't scale and is probably quite fragile using the hostname option.

Having more examples and clear examples of how to run the image on different platforms is hopefully something we will get to soon - I've not given this an awful lot of thought. This should actually be easier in a IaaS environment, where you can use `LoadBalancer` instead of `NodePort`. However, I'm not sure how that works with minikube at this point.
