### ISSUE TITLE
Up Scaling and Down Scaling

### ISSUE THREAD

**Issue by thalescm** [wurstmeister/kafka-docker#35]
## Problem
I want to test what happens to the kafka cluster when one of its servers goes down.  

### First Approach
So, what I want to do is scale kafka up to 3 servers:
```docker-compose scale kafka=3```
Then I create a topic with replication factor of 2, and 3 partitions.

It does as expected, each kafka node is the leader for a partition, and their replicas is one of the other 2 available.

But there's a problem. When scaling, docker automatically puts a random port to your host pointing to that container. So when I hit `docker-compose scale kafka=2` it removes one of the containers and kafka adjusts everything right.

But When I rescale to 3. Another port (and not the previous one) is setted to the new image and I'm not able to test if it will rebalance correctly the leadership between nodes.  

### Second Approach

I then tried to mount directly three images in `docker-compose.yml` file:
```
zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka1:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
kafka2:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9093:9093"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
kafka3:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9094:9094"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
mongodb:
  image: mongo:2.6.7
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest
  environment:
    - MONGO_URL=mongodb://mongodb:27017
```

But then I've got some problem about the volumes, which I quite couldn't understand.

Could you please help me?

**Comment by wurstmeister** [comment]
Hi, 

Thanks for raising this issue. in principle this should work if you specify the ```KAFKA_BROKER_ID``` manually rather than using the auto generated one. 

However, I've updated the way the broker id is generated which should fix this issue when using auto generated broker ids.
(https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L7)

Now you should be able to scale up and down 

Please let me know if this works for you.

**Comment by thalescm** [comment]
Hi, thanks for the help! I'll try this and let you know!

By the way, do you know how I can test with multiple zookeepers as well? I was making the test with two images ( kind of the same thing I did with multiple images of kafka above) but something happens on the links I do and when I create a topic it doesn't recognize the other kafka instances and I'm not able to set replication-factor > 1 :/

Here's the Docker-compose.yml (Note that I still didn't make the update to use only one kafka image as you suggested above):

```
zookeeper1:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
zookeeper2:
  image: wurstmeister/zookeeper
  ports:
    - "2182:2181"
kafka1:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper1:zk
    - zookeeper2:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
    KAFKA_ZOOKEEPER_CONNECT: 192.168.59.103:2181,192.168.59.103:2182
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
kafka2:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9093:9092"
  links:
    - zookeeper1:zk
    - zookeeper2:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
    KAFKA_ZOOKEEPER_CONNECT: 192.168.59.103:2181,192.168.59.103:2182
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
kafka3:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9094:9092"
  links:
    - zookeeper1:zk
    - zookeeper2:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103
    KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
    KAFKA_ZOOKEEPER_CONNECT: 192.168.59.103:2181,192.168.59.103:2182
  volumes:
      - /var/run/docker.sock:/var/run/docker.sock
mongodb:
  image: mongo:2.6.7
  ports:
    - "27017:27017"
    - "28017:28017"
  command: mongod --rest
  environment:
    - MONGO_URL=mongodb://mongodb:27017
``` 

And here's what happens when I try to create the topics

![screen shot 2015-04-27 at 11 45 06](https://cloud.githubusercontent.com/assets/4348071/7349933/e6efbe42-ecd2-11e4-927a-1ee62507e2db.png)

Thanks for your time!
