### ISSUE TITLE
Producer cannot connect inside compose-network

### ISSUE THREAD

**Issue by lostiniceland** [wurstmeister/kafka-docker#351]
After successfull development using the single-broker configuration I've created a docker-compose which should run all services.

Unfortunately my producer in serviceA is not able to connect to Kafka, though the network with regards to docker-compose is working.

```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:1.1.0
    container_name: kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      # explicitly set hostname when scaling to multiple nodes
#      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_HOST_IP:-127.0.0.1}
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_CREATE_TOPICS: "language-pit.events:1:1"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  orchestration:
    image: doesntmatterX
    depends_on:
      - kafka
    ports:
      - 9090:9090
    environment:
      BIKE_HOST: "serviceA"
      BIKE_PORT: 8080
    

  serviceA:
    image: doesntmatterA
    depends_on:
      - orchestration
    ports:
      - 8080:8080
    environment:
      KAFKA_HOST: "kafka"
      KAFKA_PORT: 9092
      KAFKA_EVENT_TOPIC: "language-pit.events"
      ORCHESTRATION_URL: "http://orchestration:9090/"
```

I've tried several solution. KAFKA_ADVERTISED_HOST and KAFKA_ADVERTISED_LISTENERS. At first I wanted Kafka to be available from within the compose-network and from the outside. As of now, I would be happy if it would at least be accessible inside.

The producer in serviceA is using "kafka:9092" for boostrap.server

```
serviceA_1           | 17:21:46.233 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Initialize connection to node kafka:9092 (id: 1008 rack: null) for sending metadata request
serviceA_1           | 17:21:46.233 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Initiating connection to node kafka:9092 (id: 1008 rack: null)
serviceA_1           | 17:21:46.234 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.common.metrics.Metrics - Added sensor with name node-1008.bytes-sent
serviceA_1           | 17:21:46.235 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.common.metrics.Metrics - Added sensor with name node-1008.bytes-received
serviceA_1           | 17:21:46.235 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.common.metrics.Metrics - Added sensor with name node-1008.latency
serviceA_1           | 17:21:46.236 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.common.network.Selector - [Producer clientId=serviceA-1] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node 1008
serviceA_1           | 17:21:46.236 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Completed connection to node 1008. Fetching API versions.
serviceA_1           | 17:21:46.236 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Initiating API versions fetch from node 1008.
serviceA_1           | 17:21:46.239 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Recorded API versions for node 1008: (Produce(0): 0 to 5 [usable: 5], Fetch(1): 0 to 7 [usable: 7], ListOffsets(2): 0 to 2 [usable: 2], Metadata(3): 0 to 5 [usable: 5], LeaderAndIsr(4): 0 to 1 [usable: 1], StopReplica(5): 0 [usable: 0], UpdateMetadata(6): 0 to 4 [usable: 4], ControlledShutdown(7): 0 to 1 [usable: 1], OffsetCommit(8): 0 to 3 [usable: 3], OffsetFetch(9): 0 to 3 [usable: 3], FindCoordinator(10): 0 to 1 [usable: 1], JoinGroup(11): 0 to 2 [usable: 2], Heartbeat(12): 0 to 1 [usable: 1], LeaveGroup(13): 0 to 1 [usable: 1], SyncGroup(14): 0 to 1 [usable: 1], DescribeGroups(15): 0 to 1 [usable: 1], ListGroups(16): 0 to 1 [usable: 1], SaslHandshake(17): 0 to 1 [usable: 1], ApiVersions(18): 0 to 1 [usable: 1], CreateTopics(19): 0 to 2 [usable: 2], DeleteTopics(20): 0 to 1 [usable: 1], DeleteRecords(21): 0 [usable: 0], InitProducerId(22): 0 [usable: 0], OffsetForLeaderEpoch(23): 0 [usable: 0], AddPartitionsToTxn(24): 0 [usable: 0], AddOffsetsToTxn(25): 0 [usable: 0], EndTxn(26): 0 [usable: 0], WriteTxnMarkers(27): 0 [usable: 0], TxnOffsetCommit(28): 0 [usable: 0], DescribeAcls(29): 0 [usable: 0], CreateAcls(30): 0 [usable: 0], DeleteAcls(31): 0 [usable: 0], DescribeConfigs(32): 0 to 1 [usable: 1], AlterConfigs(33): 0 [usable: 0], AlterReplicaLogDirs(34): 0 [usable: 0], DescribeLogDirs(35): 0 [usable: 0], SaslAuthenticate(36): 0 [usable: 0], CreatePartitions(37): 0 [usable: 0], CreateDelegationToken(38): 0 [usable: 0], RenewDelegationToken(39): 0 [usable: 0], ExpireDelegationToken(40): 0 [usable: 0], DescribeDelegationToken(41): 0 [usable: 0], DeleteGroups(42): 0 [usable: 0])
serviceA_1           | 17:21:46.240 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Sending metadata request (type=MetadataRequest, topics=language-pit.events) to node kafka:9092 (id: 1008 rack: null)
serviceA_1           | 17:21:46.242 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.Metadata - Updated cluster metadata version 3 to Cluster(id = yTyI6PkrTpK3widcCCmbpA, nodes = [kafka:9092 (id: 1008 rack: null)], partitions = [Partition(topic = language-pit.events, partition = 0, leader = none, replicas = [1001], isr = [], offlineReplicas = [1001])])
serviceA_1           | 17:21:46.343 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=serviceA-1] Sending metadata request (type=MetadataRequest, topics=language-pit.events) to node kafka:9092 (id: 1008 rack: null)
serviceA_1           | 17:21:46.345 [kafka-producer-network-thread | serviceA-1] DEBUG org.apache.kafka.clients.Metadata - Updated cluster metadata version 4 to Cluster(id = yTyI6PkrTpK3widcCCmbpA, nodes = [kafka:9092 (id: 1008 rack: null)], partitions = [Partition(topic = language-pit.events, partition = 0, leader = none, replicas = [1001], isr = [], offlineReplicas = [1001])])
```
Any help is highly appreciated since I am pretty much stuck
