### ISSUE TITLE
Kafka-docker swarm setup

### ISSUE THREAD

**Issue by jyothiballa** [wurstmeister/kafka-docker#354]
Hi,
Here is the docker compose file 

```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "curl 169.254.169.254/latest/meta-data/public-ipv4"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafkanet

networks:
    kafkanet:
```

1) docker stack deploy -c docker-compose.yml kafka-swarm
2) docker service scale kafka-swarm_kafka=3
3) docker service scale kafka-swarm_zookeeper=3
4) now i have the zookeeper quorum 
5) kafka has the automatic generated broker.id's where i am not able to create a topic with 3 replication factor and 3 partitions
i tried giving the KAFKA_BROKER_ID: 0 the same value gets populated on all the 3nodes in the swarm cluster i want unique values.

docker version:
```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    7390fc6
 Built: Tue Feb 27 22:15:20 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6
  Built:        Tue Feb 27 22:17:54 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

 OS: CentOS
