### ISSUE TITLE
Issue on docker swarm

### ISSUE THREAD

**Issue by nlybe** [wurstmeister/kafka-docker#356]
Using the docker swarm configuration I have setup a small cluster with 3 kafka brokers as follows:

```
version: '3.4'

volumes:
  kafka-logs: {}
  
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    deploy:
      mode: global
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_PROTOCOL_NAME: OUTSIDE
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_PROTOCOL_NAME: INSIDE
      KAFKA_PORT: 9092
      KAFKA_CREATE_TOPICS: "topic1:1:2,topic2:1:2,topic3:1:2"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 3600000
      KAFKA_SESSION_TIMEOUT_MS: 3600000
      MESSAGE_MAX_BYTES: 25728640
      REPLICA_FETCH_MAX_BYTES: 25728640
      MAX_REQUEST_SIZE: 25728640
      FETCH_MESSAGE_MAX_BYTES: 25728640
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-logs:/kafka
```

Everything works fine, but we have an issue. When all kafka brokers restart, the other containers on the same cluster (consumers and producers) cannot communicate with kafka anymore. The containers should be restarted in order to be able to communicate with kafka again.

I 've made some investigation and it looks like that since new kafka containers get a differebt IP, the consumers/producers try to connect to the olds IPs which of course do not exists.

I haven't setup a network for the cluster but use the default of the swarm cluster when deploy the yml file.

Any idea how to fix this is welcome.

**Comment by sscaling** [comment]
The configuration doesn't look correct to me - maybe this works for version 1.0.0 of the image). However, i'd recommend updating to the latest image version for that release (currently `2.11-1.0.1`. See the README for recent change in image tag naming).

You are using the security protocol map, but have not defined any listeners / advertised listeners which doesn't look correct.

For surviving restart have you tried setting a consistent broker ID?(https://github.com/wurstmeister/kafka-docker#broker-ids / https://kafka.apache.org/documentation/#brokerconfigs). You can confirm this by examining the kafka / producer / consumer logs to see the meta data response, or looking in zookeeper 

Without more specific steps to reproduce, logs, state information and environment configuration it's a bit hard to guess at what might be wrong.

**Comment by nlybe** [comment]
Hello @sscaling, thanks for answer.

This configuration works fine for version 1.0.0 of the image. 
I am not using BROKER_ID_COMMAND because of this volume option "**- kafka-logs:/kafka**". So the brokers keep the same broker id on each node, no matter if service/containers restarts.

We only have the issue I mentioned: when all kafka brokers restart, the other containers on the same cluster (consumers and producers) cannot communicate with kafka anymore. What we get on logs is:

```
2018-07-19 07:22:10,242 AsynchronousTask-2 ERROR Unable to write to Kafka [Kafka] for appender [Kafka]. java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.
	at org.apache.kafka.clients.producer.KafkaProducer$FutureFailure.<init>(KafkaProducer.java:769)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:490)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:436)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:356)
	at org.apache.logging.log4j.core.appender.mom.kafka.KafkaManager.send(KafkaManager.java:89)
	at org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppender.append(KafkaAppender.java:89)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
```


On zookeeper I can see the list kafka brokers and retrieve information for each of them. For example:

When everything works fine:
```
[zk: zoo1:2181(CONNECTED) 13] ls /brokers/ids      
[1003, 1002, 1001]
[zk: zoo1:2181(CONNECTED) 14] get /brokers/ids/1001
{"listener_security_protocol_map":{"OUTSIDE":"PLAINTEXT","INSIDE":"PLAINTEXT"},"endpoints":["OUTSIDE://dev-de-m2:9094","INSIDE://82681a871da1:9092"],"jmx_port":-1,"host":"dev-de-m2","timestamp":"1531985099071","port":9094,"version":4}
cZxid = 0x4d00000275
ctime = Thu Jul 19 07:24:59 GMT 2018
mZxid = 0x4d00000275
mtime = Thu Jul 19 07:24:59 GMT 2018
pZxid = 0x4d00000275
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x100000434570090
dataLength = 234
numChildren = 0
```

After restart of all kafka containers, when it doesn't work:
```
[zk: zoo1:2181(CONNECTED) 15] ls /brokers/ids      
[1003, 1002, 1001]
[zk: zoo1:2181(CONNECTED) 16] get /brokers/ids/1001
{"listener_security_protocol_map":{"OUTSIDE":"PLAINTEXT","INSIDE":"PLAINTEXT"},"endpoints":["OUTSIDE://dev-de-m2:9094","INSIDE://ecbd4814c652:9092"],"jmx_port":-1,"host":"dev-de-m2","timestamp":"1531985495693","port":9094,"version":4}
cZxid = 0x4d000003da
ctime = Thu Jul 19 07:31:35 GMT 2018
mZxid = 0x4d000003da
mtime = Thu Jul 19 07:31:35 GMT 2018
pZxid = 0x4d000003da
cversion = 0
dataVersion = 0
aclVersion = 0
ephemeralOwner = 0x1000004345700d7
dataLength = 234
numChildren = 0
```


One thing I want to confirm is the URL which I give to other applications to connect to kafka is "kafka:9092". For example the run command for java app is:
```
java -jar -Dapp.kafkaBrokers=kafka:9092 /path/to/myapp.jar
```
It works fine since they are all on the same docker swarm cluster but is this the best practice?



Finally I tried the the latest image (**2.11-1.1.0**) but it doesn't work at all, I get the following error when trying to connect to kafka: 

```
2018-07-19 06:52:19,172 main ERROR An exception occurred processing Appender Kafka org.apache.logging.log4j.core.appender.AppenderLoggingException: Unable to write to Kafka in appender: Timeout after waiting for 30000 ms.
	at org.apache.logging.log4j.core.appender.mom.kafka.KafkaAppender.append(KafkaAppender.java:92)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:447)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:432)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:416)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:402)
	...
```

The configuration I use is:

```
version: '3.4'

volumes:
  kafka-logs: {}
  
services:
  kafka:
    image: wurstmeister/kafka:1.1.0
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    deploy:
      mode: global
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "topic1:1:2,topic2:1:2,topic3:1:2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-logs:/kafka
```

Thanks in advance
