### ISSUE TITLE
How to persist data with single kafka/zookeeper instance ?

### ISSUE THREAD

**Issue by frranck** [wurstmeister/kafka-docker#360]
Hello,
Are there instructions on how to add persistency for a single kafka/zookeeper instance ?
If I add 
    _volumes:
      - /home/srv/kafka:/kafka
kafka doesn't seem to be working anymore.

**Comment by sscaling** [comment]
You can specify a logs directory in the config. If you do not, the kafka container will provide one based on the container hostname (https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L43-L45). 

Broker ID should also be consistent with logs dir so set that consistently on the node where a broker will run, or at least consistently with the logs dir.

Also worth bearing in mind the note about recreating containers in the README (https://github.com/wurstmeister/kafka-docker#broker-ids)

**Comment by frranck** [comment]
hi @sscaling,
thanks a lot f or you input, I tried with this config:

```
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      KAFKA_BROKER_ID: 1
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs-1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      **- /home/srv/kafka:/kafka/kafka-logs-1**
    depends_on:
      - zookeeper

```
It doesn't work if I include the _- /home/srv/kafka:/kafka/kafka-logs-1_ line
