### ISSUE TITLE
How can I setup retention of kafka?

### ISSUE THREAD

**Issue by Kcrong** [wurstmeister/kafka-docker#366]
Maybe related with #260 

Hi, I just updated kafka-docker by master branch.

I tried to use `KAFKA_LOG_RETENTION_MS` with 3000, but it didn't work.
Is there any way to set retention time or length for whole kafka topics?

(I know 3s is kind of short, but it's only for testing.)

Thanks.

**Comment by sscaling** [comment]
Can you explain what you mean by "didn't work" ? What tests are you running, can you provide the config and commands/checks you are using to reproduce the issue.

In the issue you linked, the information about log check interval configuration is still relevant.

**Comment by Kcrong** [comment]
@sscaling 
Sorry. I forgot to add the description below.
The issue was about even though I used `KAFKA_LOG_RETENTION_MS` with 3000, the log still remains after 5mins.

Anyways, this issue was fixed by upgrade the docker and docker-compose to the latest version.
You can close this issue.

**Comment by javieryanez** [comment]
KAFKA_LOG_RETENTION_MS doesn't work for me, but KAFKA_LOG_RETENTION_HOURS does.

**Comment by wurangbo** [comment]
@Kcrong 
Hi ,could you tell me which version ? I have the same issue.

**Comment by suiluj** [comment]
For anyone having the same issue (short retention times do not work):

You not only have to set the variable `log.retention.ms` (in the .yml `KAFKA_LOG_RETENTION_MS` but also the variable `log.retention.check.interval.ms` (in the .yml `KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS`)

`log.retention.check.interval.ms` defaults to 300000 (https://kafka.apache.org/documentation/)

So the problem was that the retention was set to a few seconds but old messages to delete where only checked every 300 seconds.

I am no kafka expert and cannot say if there is a better way but this is my configuration for test purposes (i want to get old messages deleted automatically after a few seconds so wrong messages are not stuck in the log pipeline for new kafka test clients)

I took the single broker example and changed a few lines. this is working on a mac locally:

`docker-compose-single-broker-custom-changes.yml`

```
    version: '2'
    services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
        - "2181:2181"
    kafka:
        build: .
        ports:
        - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
            KAFKA_LOG_RETENTION_MS: 10000
            KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```

As you can see messages older than 10 seconds should get deleted and this is checked every 5 seconds. I tested it and it seems to work with this configuration.

now for first start:

```
docker-compose -f docker-compose-single-broker-custom-changes.yml up -d
```

Later:

```
# stop running kafka:
docker-compose stop

# start kafka (after it was stopped in the past)
docker-compose start
```

Of course this is not a configuration for production systems.
