### ISSUE TITLE
KAFKA_MESSAGE_MAX_BYTES does not works

### ISSUE THREAD

**Issue by black-lotus** [wurstmeister/kafka-docker#367]
Hello,
I have issue to increase `message.max.bytes` 
I read the documention about add KAFKA_MESSAGE_MAX_BYTES to `environment`

```
kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

i tried to produce some big message on kafka console 
<img width="1349" alt="screen shot 2018-07-30 at 15 37 35" src="https://user-images.githubusercontent.com/3261560/43386663-8f5e85fa-940e-11e8-8618-dad148e77689.png">

and when i listner via consomer console, it get truncted
<img width="1345" alt="screen shot 2018-07-30 at 15 37 48" src="https://user-images.githubusercontent.com/3261560/43386683-9fe5edb4-940e-11e8-9ac5-458179ae7468.png">

Thank you
