### ISSUE TITLE
Not able to fetch leader. Just cloned repo. trying to run kafka cluster with 4 broker. I think internal communication is messed up. any help would be appreciated.

### ISSUE THREAD

**Issue by afterlifenirvana** [wurstmeister/kafka-docker#368]
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 171.17.0.1 # DOCKER_IP
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sa:3:1,batch_events:3:1,alerts:2:1,"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

running with 
docker-compose up --scale kafka=4 -d

**Comment by afterlifenirvana** [comment]
Running it on RHEL 7, 
connecting console consumer on 0.0.0.0:brokerport which is allotted dynamically.

**Comment by afterlifenirvana** [comment]
docker version 18.06

**Comment by sscaling** [comment]
`171.17.0.1` looks more like an internal docker IP - is that the public IP (WAN) of your host machine?

Have you looked through the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) ?

**Comment by afterlifenirvana** [comment]
It is the internal docker ip. I'm deploying containers on the same machine.

**Comment by afterlifenirvana** [comment]
on ifconfig:-
docker0: flags=4099... 
inet 172.17.0.1  ...

**Comment by afterlifenirvana** [comment]
ok I made a few changes and used these settings.

**KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://MY_PUBLIC_IP:9094
KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE**

now my consumer is able to connect to 0.0.0.0:KAFKA_PORT_ALLOCATED
but on producing messages with 0.0.0.0:KAFKA_PORT_ALLOCATED

I'm getting an error


[2018-07-30 09:36:05,144] ERROR Error when sending message to topic sa with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for sa-2: 1514 ms has passed since batch creation plus linger time

**Comment by sscaling** [comment]
that looks like the virtual docker interface. I'd expect the advertised host name to be the value of your WAN interface (most likely `eth0`). Probably a class B / class C CIDR (i.e. 192.168.x.x or 10.x.x.x) depending on the network config.

Without seeing your full configuration and the steps/commands you are using to connect to the broker it's a bit hard to help debug.

Assuming you're scaling on a single node for testing (because you're using docker-compose) you'll need to advertise the port that is exposed on the host machine (not 9094, as that will be mapped to an ephemeral port such as 32xxx range)

**Comment by afterlifenirvana** [comment]
I made the changes to the ip 
KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.x.x.x:9094
KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

my consumer is attached on 0.0.0.0:32xxx

and I'm not getting the leader not available error that means all the kafka brokers are communicating properly.

but while connecting a producer on the same 0.0.0.0:32xxx 

I'm not able to produces message.

[2018-07-30 09:36:05,144] ERROR Error when sending message to topic sa with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for sa-2: 1514 ms has passed since batch creation plus linger time

**Comment by sscaling** [comment]
You will still need to change the advertised port from 9094 -> the published port as this is all running on one machine. You can do this with the `PORT_COMMAND` (https://github.com/wurstmeister/kafka-docker#advertised-port) so you'll end up with something like

```
PORT_COMMAND: "docker port $$(hostname) 9094/tcp | cut -d: -f2"
KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.x.x.x:_{PORT_COMMAND}
```

**Comment by afterlifenirvana** [comment]
SO my final conf is something like this 
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.x.x.x:_{PORT_COMMAND}
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:_{PORT_COMMAND}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sa:3:1,batch_events:3:1,alerts:2:1,"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

I tried publishing messages via console producer with --broker-list 0.0.0.0:32xxx 
I'm still getting error
[2018-07-31 04:12:11,088] ERROR Error when sending message to topic sa with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for sa-2: 1524 ms has passed since batch creation plus linger time

zookeeper logs seems normal 

Am I doing something wrong? 
I tried docker-compose rm for a clean build but still the same problem I tried attaching producer to 10.x.x.x:32xxx still the same error. 
Anything I'm missing ?

**Comment by sscaling** [comment]
You are using the INSIDE port in the PORT_COMMAND lookup, the listeners config looks wrong and you haven't exposed the outside port. I'd expect you'd want something similar to:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "9094"
    environment:
      PORT_COMMAND: "docker port $$(hostname) 9094/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://10.10.1.5:_{PORT_COMMAND}
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sa:3:1,batch_events:3:1,alerts:2:1,"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Also, when you connect, I'd recommend specifying the actual interface that the docker bridge network has forwarded the ports from, e.g. `--broker-list 10.10.1.5:32000`
