### ISSUE TITLE
had trouble running start_kafka_shell.sh

### ISSUE THREAD

**Issue by richardwan** [wurstmeister/kafka-docker#38]
I did not know what to put in for zk_host and zk_port.  when i finally figured it out, i created a script to figure it out for me:

``` #!/bin/bash
DOCKER_IP=$(echo $DOCKER_HOST | sed -E 's/^tcp:..([^:]+):.+$/\1/g')
ZOO_CONTAINER=$(docker ps | grep zookeeper:latest | awk '{print $1}')
ZOO_PORT=$(docker port $ZOO_CONTAINER | sed -E 's/.+://g')
#echo $DOCKER_IP
#echo $ZOO_CONTAINER
#echo $ZOO_PORT
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -e HOST_IP=$DOCKER_IP -e ZK=$DOCKER_IP:$ZOO_PORT -i -t wurstmeister/kafka:0.8.2.0 /bin/bash
```

I can push this to a branch and make a PR if you give me access to the repo. the `sed -E` might only work on mac though

**Comment by Nawa** [comment]
:+1:

**Comment by nathany** [comment]
Something like this would be great. It would be even better if there was a $DOCKER_HOST_IP environment variable exposed by Docker.

Btw, when I use this docker-compose file, I don't see a zookeeper:latest under `docker ps`, just:

```console
fcfa4b69149c        wurstmeister/zookeeper       "/bin/sh -c '/usr/sb   About an hour ago   Up 48 minutes       22/tcp, 2888/tcp, 3888/tcp, 0.0.0.0:32768->2181/tcp   kafkadocker_zookeeper_1   
```

**Comment by nathany** [comment]
There are some other ways to get the IP, like `boot2docker ip` or `docker-machine ip dev` (where dev is the name of the machine). It's hard to know what to use though.

**Comment by ibizaman** [comment]
With docker compose you can do this:

```yaml
services:
    zookeeper:
        image: wurstmeister/zookeeper

    kafka:
        image: wurstmeister/kafka
        links:
            - zookeeper
        environment:
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
```
