### ISSUE TITLE
Producer Cannot Write:  "LEADER_NOT_AVAILABLE"

### ISSUE THREAD

**Issue by shuchow** [wurstmeister/kafka-docker#381]
Hello.  I'm running Docker 18.06-0-ce-mac70 on High Sierra.  I'm trying to recreate the simplest use-case "running a single Kafka broker" from the [Connectivity Wiki](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity). 

I cloned this repo and started it via:

`docker-compose -f docker-compose-single-broker.yml up -d`

Here's my docker-compose.yml file:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Everything appears fine.  Two containers will be running:
```
$ docker-compose ps
          Name                        Command               State                         Ports
----------------------------------------------------------------------------------------------------------------------
wurstmeister_kafka_1       start-kafka.sh                   Up      0.0.0.0:9092->9092/tcp
wurstmeister_zookeeper_1   /bin/sh -c /usr/sbin/sshd  ...   Up      0.0.0.0:2181->2181/tcp, 22/tcp, 2888/tcp, 3888/tcp
```

Inside the Kafka container, querying zookeeper about the topic appears normal.  The broker ID appears to match.

```
 bash-4.4# $KAFKA_HOME/bin/kafka-topics.sh --describe --topic foo --zookeeper zookeeper
Topic:foo	PartitionCount:1	ReplicationFactor:1	Configs:
	Topic: foo	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
	
bash-4.4# $KAFKA_HOME/zookeeper-shell.sh zookeeper:2181 <<< "ls /brokers/ids"
Connecting to zookeeper:2181
Welcome to ZooKeeper!
JLine support is disabled

WATCHER::

WatchedEvent state:SyncConnected type:None path:null
[1001]
```

Still inside the container, I can start a producer shell fine.  However, when I try to send something, I get a continual stream of this message:

```
WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 1 : {foo=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 2 : {foo=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 3 : {foo=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)
... and so forth
```

If I try to publish to it via a Python script on the host, it will time out and I see:

```
kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
```

Connecting to the container from the host as a Python consumer appears to work.

Any idea on what can be producing these Producer errors?
