### ISSUE TITLE
Address already in use - JMX - Kafka - Docker

### ISSUE THREAD

**Issue by meetchandan** [wurstmeister/kafka-docker#390]
Below is my docker compose file

```
version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    links:
     - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - JMX_PORT=7072
      - KAFKA_OPTS=-javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
      - KAFKA_CREATE_TOPICS=customer:1:1,audit:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka

```
When I run "docker-compose up"

I get below error:

creating topics: customer:1:1
kafka_1       | creating topics: audit:1:1
kafka_1       | Exception in thread "main" java.lang.reflect.InvocationTargetException
kafka_1       |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)Exception in thread "main" 
kafka_1       |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kafka_1       |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kafka_1       |         at java.lang.reflect.Method.invoke(Method.java:498)
kafka_1       |         at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
kafka_1       |         at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
**kafka_1       | Caused by: java.net.BindException: Address in use**
kafka_1       |         at sun.nio.ch.Net.bind0(Native Method)
kafka_1       |         at sun.nio.ch.Net.bind(Net.java:433)
kafka_1       |         at sun.nio.ch.Net.bind(Net.java:425)java.lang.reflect.InvocationTargetException
kafka_1       | 
kafka_1       |         at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
kafka_1       |         at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
kafka_1       |         at sun.net.httpserver.ServerImpl.bind(ServerImpl.java:133)
kafka_1       |         at sun.net.httpserver.HttpServerImpl.bind(HttpServerImpl.java:54)
kafka_1       |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kafka_1       |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        at io.prometheus.jmx.shaded.io.prometheus.client.exporter.HTTPServer.<init>(HTTPServer.java:83)
kafka_1       |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kafka_1       | 
kafka_1       |         at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:38)
kafka_1       |         at java.lang.reflect.Method.invoke(Method.java:498)
kafka_1       |         at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
kafka_1       |         ... 6 more      at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
kafka_1       | 
**kafka_1       | FATAL ERROR in native method: processing of -javaagent failed**
kafka_1       | Caused by: java.net.BindException: Address in use

Also, below is my docker file:
```
FROM wurstmeister/kafka
ADD prom-jmx-agent-config.yml /usr/app/prom-jmx-agent-config.yml
ADD http://central.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.10/jmx_prometheus_javaagent-0.10.jar /usr/app/jmx_prometheus_javaagent.jar
```

How can I understand which address is already in use?
