### ISSUE TITLE
docker-compose-single-broker: why advertised ip is not localhost?

### ISSUE THREAD

**Issue by holms** [wurstmeister/kafka-docker#395]
https://github.com/wurstmeister/kafka-docker/blob/39f4872641c601da0a2a7193492f61b7163a5566/docker-compose-single-broker.yml#L12

You're clearly stating in your readme that only for multiple brokers/nodes it should NOT be localhost, but in example for SINGLE broker your have host ip specified. So how should be in reality?

I   actually still don't understand why you need docker ip? And why you're exposing ports? What if I don't want to expose kafka ports and only use it in docker VPC?

**Comment by sscaling** [comment]
It completely depends on what you want to achieve. Configuring a Kafka cluster inside docker is non-trivial and requires knowledge of Kafka/Zookeeper/Docker/Docker networking etc. There are many different configurations, container runtimes, physical and virtual environments to execute in etc.

The referenced docker-compose file will allow you run a single node broker on a docker-machine host (which by default has the `192.168.99.100` IP proxied through to the docker daemon).

The [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) and the Readme to a lesser extent, explain some basic concepts.

If you want to only produce/consume from the Kafka broker within the same network then no, you do not need to expose the port publicly but will have no network isolation.

**Comment by holms** [comment]
Well 99% cases in docker is to access databases and message-ques locally by other containers :) Any  outside exposure is done with reverse proxy like traefik. In docker world we don't hardcore any outter ip's usually.

**Comment by holms** [comment]
@sscaling could you please help me? I have problem setting up your image for local usage.

Here's compose file:

```
version: '3.7'

services:

  adp-geotracking:
    image: whatever
    container_name: adp-geotracking
    environment:
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - kafka

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    labels:
      - "traefik.enable=false"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "geo-tracking-activities-v5:10:1,strava-activities-v7:10:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    expose:
      - "9092"
    depends_on:
      - zookeeper

```

I seems to be able to connect to kafka from node.js but it complains about leader election and I have no idea how to solve this.

```
adp-geotracking          | {"level":"ERROR","timestamp":"2018-09-04T20:02:11.247Z","logger":"kafkajs","message":"[Producer] There is no leader for this topic-partition as we are in the middle of a leadership election","retryCount":0,"retryTime":310}
adp-geotracking          | error: 500 - There is no leader for this topic-partition as we are in the middle of a leadership election - /feed - POST - ::ffff:172.18.0.3 undefined
adp-geotracking          | KafkaJSNumberOfRetriesExceeded: There is no leader for this topic-partition as we are in the middle of a leadership election
```
