### ISSUE TITLE
Docker for mac : LeaderNotAvailable

### ISSUE THREAD

**Issue by thiennhan2310** [wurstmeister/kafka-docker#397]
When I try to run my nodejs app on my local(not docker). It told that LeaderNotAvailble. 
I use docker for mac and your docker-composer-single-broker.yml as below

docker-composer-single-broker.yml

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "172.18.2.77"
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

producer.js

```
    const  kafka = require('kafka-node');

    var Producer = kafka.Producer,
    KeyedMessage = kafka.KeyedMessage,
    client = new kafka.Client(),
    producer = new Producer(client),
    km = new KeyedMessage('key', 'message'),
    payloads = [
        { topic: 'topic1', messages: 'hi', partition: 0 },
        { topic: 'topic2', messages: ['hello', 'world', km] }
    ];
producer.on('ready', function () {
    producer.send(payloads, function (err, data) {
        console.log(data);
        console.error(err);
    });
});

producer.on('error', function (err) {
  console.error(err)
})
```

**Comment by sscaling** [comment]
Can't really help with the nodejs library usage (however, I can't see where you specify the bootstrap servers/brokers in this config) - I would recommend trying kafkacat as that is known to be working. I'm using 1.3.1.

Also - please make sure you are using the correct IP in `KAFKA_ADVERTISED_HOST_NAME`. I think this is typically the `en0` device on a mac if you run `ifconfig` from the command line. The one you're using looks similar to an internal docker IP range so just worth checking.

**Comment by sscaling** [comment]
closing due to staleness. No update from OP.

**Comment by brandonros** [comment]
```
version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  zookeeper:
      image: wurstmeister/zookeeper
      ports:
        - "2181:2181"
  kafka:
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```

/etc/hosts
```
127.0.0.1       kafka
127.0.0.1       zookeeper
```

Same problem.
