### ISSUE TITLE
how to specific the broker list of kafka for another service  in one docker-compose.yml

### ISSUE THREAD

**Issue by Mrchenli** [wurstmeister/kafka-docker#398]
here is the my configuration, how to specific the broker list of kafka where noted with "###"

```
  kafka:
    image: dockerhub.iotbull.com:5000/iotbull-kafka:1.0.0
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep 'Node Address:' | cut -d' ' -f 4"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-monitor:
    image: dockerhub.iotbull.com:5000/kafka-offset-monitor
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
    environment:
      ZK: zookeeper:2181
      BROKER: INSIDE://:9092   ### how to specific the broker list
      MONITOR_VERSION: 0.4.6-SNAPSHOT
```
