### ISSUE TITLE
[ERROR] kafka cluster can not find leader

### ISSUE THREAD

**Issue by robihidayat** [wurstmeister/kafka-docker#409]
Hey, 
I got same error when i runing docker cluster. 

`Error while fetching metadata with correlation id 2 : {test_topic=LEADER_NOT_AVAILABLE}`

when i check log kafka, all broker id set -1. I think that make broker error. is it right ?  and how to change that parameter with docker-compose.

**Comment by sscaling** [comment]
@robihidayat  - Without more information it is impossible to help diagnose your issue.

At a minimum please provide any configuration (i.e. docker-compose files / static assets), commands used to reproduce the issue and any relevant versions (OS / docker / docker-compose etc).

It would probably help to also include the output of the broker logs as that contains the derived configuration.

**Comment by robihidayat** [comment]
@sscaling -  I use default docker-compose.yml, here's my docker-compose file. 

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```

Docker Version - Docker version 18.03.1-ce, build 9ee9f40

docker-compose version - docker-compose version 1.21.1, build 5a3f1a3

Os version - Darwin Gemahs-MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
