### ISSUE TITLE
docker swarm - pykafka.exceptions.NoBrokersAvailableError: Unable to connect to a broker to fetch metadata

### ISSUE THREAD

**Issue by maestropandy** [wurstmeister/kafka-docker#412]
I am using kafka in 3 node docker swarm setup, where my docker compose file look like as below 

```
 version: '3.2'
 services:
   zookeeper:
     image: wurstmeister/zookeeper
     ports:
       - "2181:2181"
     volumes:
       - /var/volumes/monasca/zookeeper:/tmp/zookeeper
   kafka:
     image: wurstmeister/kafka:2.11-2.0.0
     ports:
       - target: 9094
         published: 9094
         protocol: tcp
         mode: host
     environment:
       HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
       KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
       KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
       KAFKA_BROKER_ID: 1
       KAFKA_LOG_DIRS: "/kafka/kafka-logs"
       KAFKA_CREATE_TOPICS: "metrics:64:1,alarm-state-transitions:12:1,alarm-notifications:12:1,retry-notifications:3:1,events:12:1,60-seconds-notifications:3:1,kafka-health-check:1:1"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /var/volumes/monasca/kafka:/kafka
     depends_on:
       - zookeeper
 networks:
   default:
     external:
       name: DB_default
```

Where `KAFKA_BROKER_ID` & `KAFKA_LOG_DIR` are mapped and taken backup on distributed shared storage on 3 nodes.  But docker container throwing error as `pykafka.exceptions.NoBrokersAvailableError: Unable to connect to a broker to fetch metadata`
