### ISSUE TITLE
Docker  swarm compose file for 3 node cluster setup

### ISSUE THREAD

**Issue by maestropandy** [wurstmeister/kafka-docker#416]
I am having 3 node cluster setup where docker swarm is running. I would like suggestions (readymade docker file) for dockerfile to serve 3 node cluster setup.  Here below docker swarm compose file am using 

```
version: '3.2'
 services:
   zookeeper:
     image: wurstmeister/zookeeper
     ports:
       - "2181:2181"
     volumes:
       - /var/volumes/monasca/zookeeper:/tmp/zookeeper
   kafka:
     image: wurstmeister/kafka:2.11-2.0.0
     ports:
       - target: 9094
         published: 9094
         protocol: tcp
         mode: host
     environment:
       HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
       KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
       KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
       KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
       KAFKA_BROKER_ID: -1
       KAFKA_LOG_DIRS: "/kafka/kafka-logs"
       KAFKA_CREATE_TOPICS: "metrics:64:1,alarm-state-transitions:12:1,alarm-notifications:12:1,retry-notifications:3:1,events:12:1,60-seconds-notifications:3:1,kafka-health-check:1:1"
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - /var/volumes/monasca/kafka:/kafka
     depends_on:
       - zookeeper
```

and am deploying like `docker stack deploy -c docker-compose.yml kafka` but it has single broker and single zookeeper, is this right way to handle 3 node setup or need to have 3 broker different brokers and 3 zookeepers ?

**Comment by ilkerkorkut** [comment]
@maestropandy Did you created VMs via docker-machine one master and two workers , and also per node you should create kafka container. By the way, there is a wiki page https://github.com/wurstmeister/kafka-docker/wiki/Swarm , but that wiki page not included with all steps.

**Comment by rexuli** [comment]
Here is the Kafka I setup myself with docker swarm with 3 brokers and 1 zookeeper, you can take it as a reference.
```yml
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    volumes:
      - /opt/data/zookeeper:/opt/zookeeper-3.4.6/data
    ports:
      - 2181
    networks:
      custom-network:
        aliases:
          - zookeeper
  kafka-1:
    image: wurstmeister/kafka:1.1.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_DAYS: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /opt/data/kafka-1:/kafka/kafka-logs
    networks:
      custom-network:
        aliases:
          - kafka-1

  kafka-2:
    image: wurstmeister/kafka:1.1.0
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_DAYS: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /opt/data/kafka-2:/kafka/kafka-logs
    networks:
      custom-network:
        aliases:
          - kafka-2

  kafka-3:
    image: wurstmeister/kafka:1.1.0
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_DAYS: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /opt/data/kafka-3:/kafka/kafka-logs
    networks:
      custom-network:
        aliases:
          - kafka-3

networks:
  custom-network:
    external: true

```
