### ISSUE TITLE
Need help configuring kafka-docker

### ISSUE THREAD

**Issue by J2RGEZ** [wurstmeister/kafka-docker#418]
Good morning! I'm trying to create a 3 broker kafka but I've been researching for 2-3 days and nothing is working. I think this is a problem of the configuration or something. 

First of all, the context: I'm using a rails app to test kafka with [this gem](https://github.com/zendesk/ruby-kafka), but I can't create those brokers. Sometimes this error appears when I `docker-compose up -d`: 
```
ERROR: for test_kafka_1  Cannot start service kafka: Cannot link to a non running container: /test_zookeeper_1 AS /test_kafka_1/zookeeper_1

ERROR: for kafka  Cannot start service kafka: Cannot link to a non running container: /test_zookeeper_1 AS /test_kafka_1/zookeeper_1
ERROR: Encountered errors while bringing up the project.
```

Let me give you some more info:
OS: Ubuntu 18.04
Rails version: 5.2.0
Ruby version: 2.4.0

docker-compose I'm using:
```
version: '0.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.41.2
      KAFKA_CREATE_TOPICS: "test:1:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Also in dockerFile I modified this two lines:
```
ARG kafka_version=0.9.0.1
ARG scala_version=2.11
```
Any idea of what could be happening? When that error doesn't show up, I get a "timeout exception".

Note: Yesterday zookeper was fine except for timeout exceptions but now I can't make it run (since the change of kafka version)

**Comment by rexuli** [comment]
Try to start zookeeper alone and ping the address of zookeeper first.
In this case seems your zookeeper network cannot reach by the hostname you defined.

**Comment by J2RGEZ** [comment]
Update: Now I can start my brokers and zookeeper but It always shows this:
`Could not connect to any of the seed brokers: - kafka://192.168.41.2:9092: Connection timed out`

Updated docker-compose:
```
version: '0.9.0.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.41.2
      KAFKA_CREATE_TOPICS: "logpify:1:3"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
I had "kafka/0.9" in the zookeeper of image lol.

I can now ping to my containers and everything seems fine, but I still get this error :S

**Comment by rexuli** [comment]
try to remove KAFKA_ADVERTISED_HOST_NAME: 192.168.41.2

**Comment by J2RGEZ** [comment]
> try to remove KAFKA_ADVERTISED_HOST_NAME: 192.168.41.2

If I do that, I don't have any "external endpoint" to connect the client.

**Comment by J2RGEZ** [comment]
Ok I found the connection problem, here is how it looks already fixed and configured for 3 brokers:
docker-compose file:
```
version: '0.9.0.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: “test1:1:1”
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9093:9092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:0.9.0.1
    ports:
      - "9094:9092"
    links:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Now I have a different problem, and is the format of the topics. As you can see, I'm trying to auto create a topic via kafka-docker with `KAFKA_CREATE_TOPICS: “logpify1:1:1`, and now the error is the following one:
```
Error while executing topic command : Cannot convert argument '1???' of option ['replication-factor'] to class java.lang.Integer
kafka1_1     | [2018-11-04 19:58:41,763] ERROR joptsimple.OptionArgumentConversionException: Cannot convert argument '1???' of option ['replication-factor'] to class java.lang.Integer
kafka1_1     | 	at joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:237)
kafka1_1     | 	at joptsimple.OptionSet.valuesOf(OptionSet.java:226)
kafka1_1     | 	at joptsimple.OptionSet.valueOf(OptionSet.java:170)
kafka1_1     | 	at kafka.admin.TopicCommand$.createTopic(TopicCommand.scala:103)
kafka1_1     | 	at kafka.admin.TopicCommand$.main(TopicCommand.scala:60)
kafka1_1     | 	at kafka.admin.TopicCommand.main(TopicCommand.scala)
kafka1_1     | Caused by: joptsimple.internal.ReflectionException: java.lang.NumberFormatException: For input string: "1???"
kafka1_1     | 	at joptsimple.internal.Reflection.reflectionException(Reflection.java:136)
kafka1_1     | 	at joptsimple.internal.Reflection.invoke(Reflection.java:123)
kafka1_1     | 	at joptsimple.internal.MethodInvokingValueConverter.convert(MethodInvokingValueConverter.java:48)
kafka1_1     | 	at joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:234)
kafka1_1     | 	... 5 more
kafka1_1     |  (kafka.admin.TopicCommand$)
```
Any ideas?

**Comment by rexuli** [comment]
@J2RGEZ try to use auto create topic first

**Comment by sscaling** [comment]
1. You are using a **very** old version of the image (> 3 years). So you should update to the latest 0.9.x branch if you **need** to use a version that old. Otherwise I'd recommend updating to a later version. FYI: `wurstmeister/kafka:2.11-0.9.0.1` should be the most recent 0.9.x image.
2. Your configuration looks incorrect

   ```
   kafka2:
     ports:
       - "9093:9092"
     environment:
       ... snip ...
       KAFKA_ADVERTISED_PORT: 9093
   ```

   You've explicitly set the advertised port to `9093`, but then forwarded the host-port to `9092`. I'd expect the port configuration to be `- "9093:9093"`

**Comment by J2RGEZ** [comment]
Still can't find a solution. @sscaling the way you say is not working for me. Right now I can see my topics with my client but I can't produce or consume anything. My docker-compose.yml file:

```
version: '2'
services:
  zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.4:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9093:9093"
    links:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.3:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9094:9094"
    links:
      - zookeeper
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.19.0.5:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

My client:
```
kafka_client = Kafka.new(seed_brokers: ["172.19.0.3:9093",
      "172.19.0.4:9092",
      "172.19.0.5:9094"],
      client_id: "Logpify_app", logger: Logger.new(STDOUT))
```

**Comment by J2RGEZ** [comment]
If you mean this, I'm getting a connection time out from my client:
docker-compose.yml:
```
version: '2'
services:
  zookeeper:
   image: wurstmeister/zookeeper
   ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: my_public_ip
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9093:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: my_public_ip
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka3:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9094:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: my_public_ip
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
My client (this is out of the docker, on my rails app):
```
kafka_client = Kafka.new(seed_brokers: ["85.155.38.231:9092","85.155.38.231:9093",
    "85.155.38.231:9094"],
      client_id: "Logpify_app", logger: Logger.new(STDOUT))
```
