### ISSUE TITLE
Crash on start using 

### ISSUE THREAD

**Issue by dag24** [wurstmeister/kafka-docker#429]
Latest docker image (2.12-2.1.0) on dockerhub fails on startup with:
```
[2018-11-22 11:39:58,880] INFO [KafkaServer id=1001] started (kafka.server.KafkaServer)
[2018-11-22 11:39:58,993] ERROR Caught unexpected throwable (org.apache.zookeeper.ClientCnxn)
java.lang.NullPointerException
        at kafka.zookeeper.ZooKeeperClient$$anon$10.processResult(ZooKeeperClient.scala:234)
        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:633)
        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:508)
```

Downgrading to wurstmeister/kafka:2.11-2.0.1 works.

Please let me know what further information would be useful to provide.

**Comment by dag24** [comment]
docker version:

```
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:51 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:55:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

docker-compose version:
```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

Host OS: Windows 10 (Version 1803, Build 17134.407)

I should point out that I am using zetcd+etcd to "simulate" Zookeeper.

Minimal docker-compose file to reproduce:

```
version: "2.1"
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zetcd:2181

  etcd0:
    image: quay.io/coreos/etcd:latest
    ports:
      - "2379:2379"
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd0
      - -advertise-client-urls
      - http://localhost:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://localhost:2380
      - -listen-peer-urls
      - http://localhost:2380
      - -initial-cluster
      - etcd0=http://localhost:2380

  zetcd:
    image: quay.io/coreos/zetcd
    depends_on:
      etcd0:
        condition: service_started
    ports:
      - "2181:2181"
    command:
      - -endpoints
      - http://etcd0:2379
```

Output from `docker-compose up`: https://gist.github.com/dag24/a90995dbdddafe21e18ec3cb6ea0e69c

Observe that changing the kafka image label to `2.11-2.0.1` results in an error-free startup.
