### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by gokhansari** [wurstmeister/kafka-docker#435]
I try to join two stream by using  **Kafka Streams**. While using **multiple** broker with wurstmeister/kafka, Kafka Stream shutdown itself and does not throw any exception if you do not set **UncaughtExceptionHandler** handler. I got this one below after setting handler:

> java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni7105115125614966504.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni7105115125614966504.so)

I made a few research about this and I think It is related with the libc6-compat version of the wurstmeister/kafka base image . 

Note: Did not face this problem with single broker.

**Comment by sscaling** [comment]
Can you provide some more information? This is the first report of this, which I would have expected to see before now.

What version of kafka-docker are you running? What OS are you running / version of docker (`docker inspect --format '{{json .Config.Labels }}' <image name>`)

We use glibc (libc6-compat is musl). This issue would indicate they are not compatible packages (https://github.com/sgerrand/alpine-pkg-glibc/issues/51)

This seems somewhat related: https://issues.apache.org/jira/browse/KAFKA-4988 (albeit the solution is to use anapsix-java - which is essentially what our base image is: alpine + glibc. They do use oracle JDK rather than openJDK though)

Have you got a small reproducible example application / set of steps, that can be used to debug this further?

Also, have you tried with musl, rather than glibc?

**Comment by talhaocakci** [comment]
I have the same problem.

kafka-docker version: 2.12_2.1.0
Os version: Ubuntu 16.04.3 LTS (Xenial Xerus)x86_64 x86_64 x86_64 GNU/Linux

**Comment by sscaling** [comment]
As a starting point, here is a simple join of two streams (just concatenate their value into one stream)

```
        String letters = "letters";
        String numbers = "numbers";

        Properties props = new Properties();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9094,localhost:9095");
        props.put(StreamsConfig.APPLICATION_ID_CONFIG, "streams-join-test");
        props.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass());
        props.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass());


        StreamsBuilder builder = new StreamsBuilder();

        KStream<String, String> left = builder.stream(letters);
        KStream<String, String> right = builder.stream(numbers);

        KStream<String, String> joined = left.join(right,
                (lval, rval) -> lval + "+" + rval,
                JoinWindows.of(Duration.ofSeconds(5)),
                Joined.with(
                        Serdes.String(),
                        Serdes.String(),
                        Serdes.String())
        );

        joined.to("output");

        new KafkaStreams(topology.build(), props).start();
```

I have a docker-compose, such as:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka1:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9094:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.3
      KAFKA_ADVERTISED_PORT: 9094
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka2:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9095:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.3
      KAFKA_ADVERTISED_PORT: 9095
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

I created the two kafka input topics (letters + numbers) with `--partitions 10 --replication-factor 1` so that data is distributed between the two brokers:

```
bash-4.4# kafka-topics.sh --describe --zookeeper zookeeper
Topic:letters	PartitionCount:10	ReplicationFactor:1	Configs:
	Topic: letters	Partition: 0	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: letters	Partition: 1	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: letters	Partition: 2	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: letters	Partition: 3	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: letters	Partition: 4	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: letters	Partition: 5	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: letters	Partition: 6	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: letters	Partition: 7	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: letters	Partition: 8	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: letters	Partition: 9	Leader: 1002	Replicas: 1002	Isr: 1002
Topic:numbers	PartitionCount:10	ReplicationFactor:1	Configs:
	Topic: numbers	Partition: 0	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: numbers	Partition: 1	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: numbers	Partition: 2	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: numbers	Partition: 3	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: numbers	Partition: 4	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: numbers	Partition: 5	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: numbers	Partition: 6	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: numbers	Partition: 7	Leader: 1001	Replicas: 1001	Isr: 1001
	Topic: numbers	Partition: 8	Leader: 1002	Replicas: 1002	Isr: 1002
	Topic: numbers	Partition: 9	Leader: 1001	Replicas: 1001	Isr: 1001
```

I populated input data using kafkacat:

```
echo -e "a:a\nb:b" | kafkacat -b localhost:9094 -P -t letters -K:
echo -e "a:2\nb:3" | kafkacat -b localhost:9094 -P -t numbers -K:
```
The output stream is generated successfully

```
$ kafkacat -b localhost:9094 -C -t output -f '%k: %s\n' -o beginning
b: b+3
a: a+2
```

This works fine for me. How different is your application? can you get your issue down to the minimum set of steps to reproduce it?

Thanks.

**Comment by talhaocakci** [comment]
I have tried your minimal configuration with success. I moved it one step further with our implementation which has complex keys and values again with success. Then I tried it with our kafka configuration with failure.
Our configuration is below:

 kafka:                                                                                                
        image: wurstmeister/kafka                                                                         
        networks:                                                                                         
            - internal                                                                                    
        ports:                                                                                            
            - target: 9094                                                                                
              published: 9094                                                                             
              protocol: tcp                                                                               
              mode: host                                                                                  
        environment:                               
            KAFKA_ZOOKEEPER_CONNECT: zk:2181       
            # KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            HOSTNAME_COMMAND: wget -t3 -T2 -qO- http://169.254.169.254/latest/meta-data/local-ipv4
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094         
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094                                       
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT              
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE                                              
            KAFKA_LOGS_DIR: /kafka/logs                                                           
        volumes:                                                                                  
            - kafka_data:/kafka                                                                   
        deploy:                                                                                   
            mode: global                                                                          
            placement:                                                                            
                constraints:                                                                      
                    - node.labels.kafka == true

**Comment by sscaling** [comment]
@talhaocakci - My first observation is that you're deploying this to a Swarm cluster (you're specifying the `deploy` config) - and running this inside AWS (given the use of the metadata service for hostname). Is this correct? If so @gokhansari - are you also running this on Swarm? Have you tried with my minimal config.

@talhaocakci - have you verified your configuration works for non-streams application? I.e. just connecting with Kafkacat and verifying you can produce / consume without error? 

Are you seeing the exact same error as @gokhansari?

> java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni7105115125614966504.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/librocksdbjni7105115125614966504.so)

**Comment by tunix** [comment]
@sscaling We're working on the same project with @talhaocakci and @gokhansari and yes, all your findings are true. We're deploying onto Swarm in AWS and just this application (with joins etc) doesn't work. The rest produce & consume messages just fine.

**Comment by sscaling** [comment]
Unfortunately without any further information I don't think I can offer any more assistance at this point. If you can provide an example that consistently reproduces the error then I can try and find time to investigate further. 

I would need:
* The kafka-docker version `docker inspect --format '{{json .Config.Labels }}' <image name>`
* code for the streams application that breaks
* input data example
* node configuration (as this is AWS, the AMI ID if it's public - failing that base OS, docker daemon version etc)
* Any commands used to create the pre-requisites (such as topics)
* Commands use to deploy and scale the Swarm stack.

**Comment by tunix** [comment]
@sscaling I just found out that the problem was the lack of `libc6-compat` package in streaming app's container. Thanks for your help! We may close this ticket.

**Comment by kennethtxytqw** [comment]
In case any one is interested, this is the reason why: https://stackoverflow.com/a/51655643/7068957

**Comment by gborobio73** [comment]
Hello, 
I'm having this exact same issue when joining a KStream and KTable using spring cloud stream. I'm running kafka as a single broker.
Here's my docker compose file:
```
version: "3.4"
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "user-clicks:1:1, user-regions:1:1, output-topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  connect:
    container_name: connect
    image: debezium/connect:1.1
    ports:
      - 8083:8083
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

networks:
  default:
    external:
      name: test
```
Here's my spring cloud stream app
```
package com.tablejoin;

import java.time.Duration;
import java.util.Properties;
import java.util.function.BiFunction;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.Serdes;
import org.apache.kafka.streams.KeyValue;
import org.apache.kafka.streams.StreamsBuilder;
import org.apache.kafka.streams.StreamsConfig;
import org.apache.kafka.streams.kstream.Grouped;
import org.apache.kafka.streams.kstream.JoinWindows;
import org.apache.kafka.streams.kstream.Joined;
import org.apache.kafka.streams.kstream.KStream;
import org.apache.kafka.streams.kstream.KTable;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import org.apache.kafka.streams.KafkaStreams;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.common.serialization.Serdes;

@SpringBootApplication
public class TableJoinApplication {

	public static void main(String[] args) {
		SpringApplication.run(TableJoinApplication.class, args);
	}

	public static class KStreamToTableJoinApplication {

		@Bean
		public BiFunction<KStream<String, Long>, KTable<String, String>, KStream<String, Long>> process() {

			return (userClicksStream, userRegionsTable) -> userClicksStream
					.leftJoin(userRegionsTable,
							(clicks, region) -> new RegionWithClicks(region == null ? "UNKNOWN" : region, clicks),
							Joined.with(Serdes.String(), Serdes.Long(), null))
					.map((user, regionWithClicks) -> new KeyValue<>(regionWithClicks.getRegion(), regionWithClicks.getClicks()))
					.groupByKey(Grouped.with(Serdes.String(), Serdes.Long()))
					.reduce((firstClicks, secondClicks) -> firstClicks + secondClicks)
					.toStream();
		}
	}

	private static final class RegionWithClicks {

		private final String region;
		private final long clicks;

		public RegionWithClicks(String region, long clicks) {
			if (region == null || region.isEmpty()) {
				throw new IllegalArgumentException("region must be set");
			}
			if (clicks < 0) {
				throw new IllegalArgumentException("clicks must not be negative");
			}
			this.region = region;
			this.clicks = clicks;
		}

		public String getRegion() {
			return region;
		}

		public long getClicks() {
			return clicks;
		}

	}
}
```
It's the example from https://github.com/spring-cloud/spring-cloud-stream-samples/blob/master/kafka-streams-samples/kafka-streams-table-join/src/main/java/kafka/streams/table/join/KafkaStreamsTableJoin.java

here's my application.yaml file where I have the spring conf
```
spring.cloud.stream.kafka.binder:
    brokers: kafka:9092

spring.application.name: stream-table-sample

spring.cloud.stream.bindings.process-in-0:
  destination: user-clicks
spring.cloud.stream.bindings.process-in-1:
  destination: user-regions
spring.cloud.stream.bindings.process-out-0:
  destination: output-topic

spring.cloud.stream.kafka.streams.binder:
  configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000
```

When I start the application with `/mvnw spring-boot:run` it fails with:
```
 Exception in thread "stream-table-sample-17caeb9f-d5a5-4854-b84c-980f2e430472-StreamThread-1" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5141886874817830091.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/librocksdbjni5141886874817830091.so)
```
I would really appreciate your help. Thanks a lot!
