### ISSUE TITLE
How to set log.retention.minutes?

### ISSUE THREAD

**Issue by wjzhangcsu** [wurstmeister/kafka-docker#439]
I want to set log.retention.minutes and restart kafka，how should I do?

**Comment by sscaling** [comment]
I'm not entirely sure what you mean? Are they two separate questions, e.g.

How do I
1. Set `log.retention.minutes`
2. Restart Kafka

Or are you asking how to change that configuration on a running broker?

The [README](https://github.com/wurstmeister/kafka-docker#pre-requisites) documents how to configure broker properties:

> if you want to customize any Kafka parameters, simply add them as environment variables in docker-compose.yml, e.g. in order to increase the message.max.bytes parameter set the environment to KAFKA_MESSAGE_MAX_BYTES: 2000000. 

Restarting Kafka can have a different effect depending on your configuration. If it's just a test cluster and you don't care about the data, i'd suggest tearing everything down (Kafka and Zookeeper) then starting a new cluster with the required configuration.

**Comment by suiluj** [comment]
I want to do the same. I added the enviroment variable to the docker-compose.yml but it did not show any effect. I produced some messages in Kafka and waited longer than one minute. Then i started a consumer and the consumer got all messages even the messages which were older than 1 minute.

Here my configuration:

```
    version: '2'
    services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
        - "2181:2181"
    kafka:
        build: .
        ports:
        - "9092:9092"
        environment:
        KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
        LOG_RETENTION_MINUTES: 1
        KAFKA_CREATE_TOPICS: "test:1:1,trafficmqtt:1:1:compact"
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
```

Does anyone have a solution? I want to have this kind of small retention time. I use this configuration for test purposes.
