### ISSUE TITLE
Can no longer build and run 1.0.0

### ISSUE THREAD

**Issue by vgjenks** [wurstmeister/kafka-docker#441]
About a year ago when we embarked upon our Kafka implementation, we began to direct developers to use your implementation in their local development setup.

I essentially took the documents from this repo and we use them to launch the container(s).

In the last couple of weeks, we're seeing failures when new devs try to build and run from those same files. The "old timers" aren't having the same issue - including myself.

We're on 1.0.0 in production so we'd like to not have to start over w/ latest, if possible.

When we run it now on new machines, we see this:

`ERROR: Service ‘my-kafka’ failed to build: The command ‘/bin/sh -c apk add --update unzip wget curl docker jq coreutils  && chmod a+x /tmp/*.sh  && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin  && /tmp/download-kafka.sh  && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt  && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz  && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka  && rm /tmp/*’ returned a non-zero code: 8`

Here's our Dockerfile:

```
FROM anapsix/alpine-java

ARG kafka_version=1.0.0
ARG scala_version=2.12

MAINTAINER wurstmeister

ENV KAFKA_VERSION=$kafka_version \
    SCALA_VERSION=$scala_version \
    KAFKA_HOME=/opt/kafka \
    PATH=${PATH}:${KAFKA_HOME}/bin

COPY download-kafka.sh start-kafka.sh broker-list.sh create-topics.sh /tmp/

RUN apk add --update unzip wget curl docker jq coreutils \
 && chmod a+x /tmp/*.sh \
 && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /usr/bin \
 && /tmp/download-kafka.sh \
 && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt \
 && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
 && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka \
 && rm /tmp/*

VOLUME ["/kafka"]

# Use "exec" form so that it runs as PID 1 (useful for graceful shutdown)
CMD ["start-kafka.sh"]
```

Here's our docker-compose file:

```
version: '3'
services:
  my-zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  my-kafka:
    build: .
    ports:
      - "9092:9092"
    hostname: my-kafka
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_HOST_NAME: my-kafka
      KAFKA_ZOOKEEPER_CONNECT: my-zookeeper:2181
      KAFKA_CREATE_TOPICS: "mytopic1:1:1,mytopic2:1:1,etc:1:1"
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /opt/kafka/docker.sock:/var/run/docker.sock  
```

We didn't change anything else. Would really appreciate some help getting this running again, thanks!
