### ISSUE TITLE
mount server.properties

### ISSUE THREAD

**Issue by ZMMWMY** [wurstmeister/kafka-docker#443]
i want to mount server.properties .but when i run the image .i get error log 
here is my docker-compose.yml
```
version: '2'
services:
  zk:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka-1:
    image: wurstmeister/kafka
    depends_on: [ zk ]
    ports:
      - "9093:9092"
    volumes:
      - "/root/kafka-no-secure/kafka/log.dirs/:/kafka/logs/"
      - "/root/kafka-no-secure/kafka/config/server.properties:/opt/kafka_2.11-2.0.0/config/server.properties"
    environment:
      KAFKA_LOG_DIRS: "/kafka/logs"
      KAFKA_ADVERTISED_HOST_NAME: xx.xx.xx.xx
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
```
logs 
```
Excluding KAFKA_HOME from broker config
[Configuring] 'advertised.host.name' in '/opt/kafka/config/server.properties'
[Configuring] 'default.replication.factor' in '/opt/kafka/config/server.properties'
[Configuring] 'port' in '/opt/kafka/config/server.properties'
[Configuring] 'broker.id' in '/opt/kafka/config/server.properties'
sed: can't move '/opt/kafka/config/server.propertiesMjkgLp' to '/opt/kafka/config/server.properties': Resource busy
```
