### ISSUE TITLE
Kafka consumer never reads messages sent to a topic

### ISSUE THREAD

**Issue by lozuwa** [wurstmeister/kafka-docker#445]
Hello,
I have mounted a cluster with three kafka nodes and a single zookeeper. After testing a consumer and a producer with automatic topic creation, I realized that no messages are ever read in the consumer. However if I run 

<b>kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list kafka-1:9092 --topic my-topic-test --time -1</b>

I can see the messages are stored in the partitions. 
However, even if I run

<b>kafka-console-consumer --bootstrap-server kafka-1:9092 --topic my-topic-test --from-beginning</b>

No messages are processed.

By the way, this same example works without any issue with the original confluent kafka and zookeeper images.

Thanks for the help

**Comment by sscaling** [comment]
"confluent" Kafka is a separate image maintained by https://www.confluent.io/. Its bootstrap process is similar but not identical to this image, so shouldn't be compared.

Without more information on your setup, configuration, orchestration layer, version, host OS, logs and commands used to run your tests it is impossible to offer any advice on what you have configured incorrectly.

**Comment by lozuwa** [comment]
Thanks for the help.

<b>Host OS:</b> Ubuntu 16.04

<b>Test commands:</b>
1. <b>Start docker-compose:</b> docker-compose up -d
2. <b>Enter one of the containers:</b> docker exec -it CONTAINER_ID bash
3. <b>Create a consumer:</b> kafka-console-consumer.sh --bootstrap-server kafka-1:9092 --topic test
4. <b>Create a producer:</b> kafka-console-producer.sh --broker-list kafka-1:9092 --topic test
5. Writing messages in the producer, but nothing appears in the consumer.

<b>kafka-1 logs (looks like the error)</b>
kafka-1_1_aef051ea9be0 | [2018-12-27 16:08:47,820] INFO [GroupCoordinator 1]: Stabilized group console-consumer-35635 generation 1281 (__consumer_offsets-23) (kafka.coordinator.group.GroupCoordinator)

kafka-1_1_aef051ea9be0 | [2018-12-27 16:08:47,820] INFO [GroupCoordinator 1]: Assignment received from leader for group console-consumer-35635 for generation 1281 (kafka.coordinator.group.GroupCoordinator)

kafka-1_1_aef051ea9be0 | [2018-12-27 16:08:47,821] ERROR [ReplicaManager broker=1] Error processing append operation on partition __consumer_offsets-23 (kafka.server.ReplicaManager)

kafka-1_1_aef051ea9be0 | org.apache.kafka.common.errors.NotEnoughReplicasException: The size of the current ISR Set(1) is insufficient to satisfy the min.isr requirement of 2 for partition __consumer_offsets-23

kafka-1_1_aef051ea9be0 | [2018-12-27 16:08:47,821] INFO [GroupCoordinator 1]: Preparing to rebalance group console-consumer-35635 in state PreparingRebalance with old generation 1281 (__consumer_offsets-23) (reason: error when storing group assignment during SyncGroup (member: consumer-1-32e4bb68-f408-4644-8508-97351957ce1c)) (kafka.coordinator.group.GroupCoordinator)

<b>docker-compose file</b>:

```yml
version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    volumes:
      - /opt/data/zookeeper:/opt/zookeeper-3.4.6/data
    ports:
      - "2181:2181"
    networks:
      custom-network:
        aliases:
          - zookeeper
  kafka-1:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_DAYS: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      # Confluent configurations
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      # Replications
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # Partitions
      KAFKA_NUM_PARTITIONS: 20
      # Others
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    ports:
      - "9092:9092"
    volumes:
      - /opt/data/kafka-1:/kafka/kafka-logs
    networks:
      custom-network:
        aliases:
          - kafka-1

  kafka-2:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_DAYS: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      # Confluent configurations
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      # Replications
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # Partitions
      KAFKA_NUM_PARTITIONS: 20
      # Others
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    ports:
      - "9093:9092"
    volumes:
      - /opt/data/kafka-2:/kafka/kafka-logs
    networks:
      custom-network:
        aliases:
          - kafka-2

  kafka-3:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
      KAFKA_LISTENERS: INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_RETENTION_BYTES: -1
      KAFKA_LOG_RETENTION_DAYS: 2
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      # Confluent configurations
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      # Replications
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      # Partitions
      KAFKA_NUM_PARTITIONS: 20
      # Others
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_MIN_INSYNC_REPLICAS: 2
    ports:
      - "9094:9092"
    volumes:
      - /opt/data/kafka-3:/kafka/kafka-logs
    networks:
      custom-network:
        aliases:
          - kafka-3

networks:
  custom-network:
    external: true
```

**Comment by lozuwa** [comment]
Setting a MIN_INSYNC_REPLICATION to 1 solved the issue that seems to be related to this: <a>https://issues.apache.org/jira/browse/KAFKA-4446</a> which is still a problem with the latest wurtsmeister image

**Comment by sscaling** [comment]
I'm not familiar with this specific issue - the linked ticket looks unrelated as it's about the `offsets.topic.replication.factor` config not being enforced correctly (see the ticket the one you linked to duplicates - https://issues.apache.org/jira/browse/KAFKA-3959)

As you have not specified this configuration, you'd need to cross reference with the configured value of your broker. When I run the latest image, I check with:

```
$ docker-compose logs | grep offsets.topic.replication.factor
kafka_2      | 	offsets.topic.replication.factor = 1
kafka_3      | 	offsets.topic.replication.factor = 1
kafka_1      | 	offsets.topic.replication.factor = 1
```

So you may want to try that as 3.

I tried with a local cluster of 3 brokers and I had no issue producing / consuming from the topics

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 20
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 3000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: 'true'
      KAFKA_CONTROLLER_SHUTDOWN_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

```
$ docker-compose up -d
$ docker-compose scale kafka=3
$ echo "hello" | kafkacat -b localhost:32779,localhost:32778,localhost:32777 -P -t test
$ kafkacat -b localhost:32779,localhost:32778,localhost:32777 -C -t test -e
hello
```

As far as I can tell from your description and comments there is no issue with the image, just the configuration, so I will close this issue. Please re-open if you think there is an issue with the image and can provide a minimal set of steps and configuration files to reproduce. 

Of course if you think you've found an issue + solution, PRs are always welcome.

Thanks.

--- 

As an aside, all three Kafka brokers are configured with the same listeners and advertised.listeners. (`KAFKA_LISTENERS: INSIDE://:9092`). As per the [advertised.listeners official docs](https://kafka.apache.org/documentation/#brokerconfigs)

> If this is not set, the value for listeners will be used

So all three brokers are binding to port 9092, but you publish different ports on each of the three brokers. So if you produce / consume from outside the docker network this is associated with, this is a little confusing - your examples do not.
