### ISSUE TITLE
when container start mkdir: can't create directory error

### ISSUE THREAD

**Issue by audtjddld** [wurstmeister/kafka-docker#459]
hi 

I cloned this repository and started the container.
An error has occurred.

![image](https://user-images.githubusercontent.com/6148003/52388768-43794d80-2ad3-11e9-86e6-759b12470b52.png)

my docker-compose-single.yml  is below

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

How can this problem be solved?
