### ISSUE TITLE
can not connect to kafka from out side nodejs

### ISSUE THREAD

**Issue by adonisrayan** [wurstmeister/kafka-docker#482]
it's my docker configuration:

```
  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"`
```

and it's a part of my node js code 

```
producer.on('ready', function () {
    console.log("here");
    producer.send(payloads, function (err, data) {
        console.log(data);
    });

});
```

when i tried to connect to kafka form node js to create a topic, everything is ok, but when i want to produce data, "here" has been printed but after 30 seconds timeout has been occurred /
