### ISSUE TITLE
Can't create a topic with multiple partitions using KAFKA_CREATE_TOPICS

### ISSUE THREAD

**Issue by reugn** [wurstmeister/kafka-docker#490]
docker-compose file:
```
version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "test:3:1,test2:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Both topics are created with a single partition.
