### ISSUE TITLE
Consumer fail to read any message after kafka restart

### ISSUE THREAD

**Issue by gerassimos** [wurstmeister/kafka-docker#492]
Using the docker swarm configuration I have setup single node cluster with 1 kafka broker as follows:

```yml
kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
      - zookeeper
    networks:
      - net-broker
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
    # ports:
    #   - target: 9094
    #     published: 9094
    #     protocol: tcp
    #     mode: host
    environment:
      HOSTNAME_COMMAND: "echo ${HOST_IP:-192.168.99.100}"
      KAFKA_CREATE_TOPICS: "gnss-topic-${GNSS_TAG}:3:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      BROKER_ID_COMMAND: "echo 101"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka-data:/kafka
    logging:
      driver: "json-file"
      options:
        max-size: "${GNSS_LOG_SIZE:-100m}"
        max-file: "${GNSS_LOG_MAX_FILES:-3}"
  ```

 - The consumer and the producer (spring boot micro-services) are on the same overlay network "net-broker" and so they access kafka with the service name "kafka:9092"
 - Everything is working fine on the first start.
 - Then kafka ONLY is restarted and after that the consumer and the producer are not able to send or read messages from kafka topic any more.
 - The kafka service is restarted due to a small change in the docker-compose.yml (e.g max_attempts: 3 => max_attempts: 4) 

 - Note: that I do not want to access kafka from outside the overlay network and I would like not to expose any port on the Docker host machine and this is why the `ports` section is commented out 

Kafka logs after restart:
```console
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | [2019-05-08 09:42:47,640] INFO [GroupMetadataManager brokerId=101] Finished loading offsets and group metadata from __consumer_offsets-45 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | [2019-05-08 09:42:47,640] INFO [GroupMetadataManager brokerId=101] Finished loading offsets and group metadata from __consumer_offsets-48 in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | creating topics: gnss-topic-11.2.1-B5607:3:1
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | [2019-05-08 09:42:57,639] INFO [GroupCoordinator 101]: Member consumer-1-9801359e-68be-41f6-bead-7c540f8f3b04 in group gnss-view-data has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | [2019-05-08 09:42:57,645] INFO [GroupCoordinator 101]: Preparing to rebalance group gnss-view-data in state PreparingRebalance with old generation 1 (__consumer_offsets-18) (reason: removing member consumer-1-9801359e-68be-41f6-bead-7c540f8f3b04 on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
gnss_kafka.1.ifspcnjob1fv@GDN-S-GNSS2    | [2019-05-08 09:42:57,650] INFO [GroupCoordinator 101]: Group gnss-view-data with generation 2 is now empty (__consumer_offsets-18) (kafka.coordinator.group.GroupCoordinator)
```

spring boot producer logs:
```console
org.apache.kafka.common.errors.TimeoutException: Expiring 1 record(s) for gnss-topic-11.2.1-B5607-1: 30030 ms has passed since batch creation plus linger time
```

spring boot consumer logs:
```console
gnss_data-access.1.ll948jogpqil@GDN-S-GNSS2    | 2019-05-08 09:42:33.984  INFO 1 --- [ gnss-view-data] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=consumer-1, groupId=gnss-view-data] Marking the coordinator fe7091944126:9092 (id: 2147483546 rack: null) dead
```
From the above log I can see that the consumer is using the container ID `fe7091944126:9092` instead of the service name `kafka:9092`. I do not know why. 

I am using the 'spring-kafka-2.1.7.RELEASE.jar' library for the producer/consumer microservice

```console
# docker ps -a 
...
fe7091944126        wurstmeister/kafka:2.12-2.2.0                                           "start-kafka.sh"         32 minutes ago      Exited (143) 28 minutes ago                                  gnss_kafka.1.xar2unhmxd4x03zbrhqllmzae
...
```
