### ISSUE TITLE
Why is there a zombie process in the container?

### ISSUE THREAD

**Issue by sjt157** [wurstmeister/kafka-docker#497]
![1558757495(1)](https://user-images.githubusercontent.com/15856742/58364356-d228a380-7ee5-11e9-9f30-aa048c320b14.jpg)
![1558757634(1)](https://user-images.githubusercontent.com/15856742/58364366-fe442480-7ee5-11e9-99dd-ba503c23d565.jpg)
![1558757682(1)](https://user-images.githubusercontent.com/15856742/58364381-2af83c00-7ee6-11e9-91ec-1c8fdd6f7e15.jpg)

platform： Ubuntu 16.04

docker-compose.yml 

```yml
version: '2.1'

services:
  kafka1:
    image: wurstmeister/kafka:2.12-2.0.1
    restart: always
    hostname: kafka4
    container_name: kafka4
    ports:
    - 9097:9092
    environment:
  
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka4:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka4:9092
      KAFKA_BROKER_ID: 18
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
       #6 partition and 3 replicas
      KAFKA_CREATE_TOPICS: "wave2018021:6:3,wave2018031:6:3,wave2018041:6:3"
    volumes:
    - /home/ubuntu16/Docker/data/kafka1:/kafka
    - /home/ubuntu16/Docker/logs/kafka1:/opt/kafka/logs
    external_links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      mybridge:
        ipv4_address: 172.18.20.230

  kafka2:
    image: wurstmeister/kafka:2.12-2.0.1
    restart: always
    hostname: kafka5
    container_name: kafka5
    ports:
    - 9098:9092
    environment:
     # KAFKA_ADVERTISED_HOST_NAME: kafka2
     # KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka5:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka5:9092
      KAFKA_BROKER_ID: 19
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_CREATE_TOPICS: "taxi1:6:3"
    volumes:
    - /home/ubuntu16/Docker/data/kafka2:/kafka
    - /home/ubuntu16/Docker/logs/kafka2:/opt/kafka/logs
    external_links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      mybridge:
        ipv4_address: 172.18.20.231

  kafka3:
    image: wurstmeister/kafka:2.12-2.0.1
    restart: always
    hostname: kafka6
    container_name: kafka6
    ports:
    - 9099:9092

    environment:
     # KAFKA_ADVERTISED_HOST_NAME: kafka3
     # KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka6:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka6:9092
      KAFKA_BROKER_ID: 20
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_CREATE_TOPICS: "camera1:6:3"
    volumes:
    - /home/ubuntu16/Docker/data/kafka1:/kafka
    - /home/ubuntu16/Docker/logs/kafka1:/opt/kafka/logs
    external_links:
    - zoo1
    - zoo2
    - zoo3
    networks:
      mybridge:
        ipv4_address: 172.18.20.232

networks:
  mybridge:
    external:
      name: mybridge
```
