### ISSUE TITLE
Error with KAFKA_JMX_OPTS

### ISSUE THREAD

**Issue by alvarolmedo** [wurstmeister/kafka-docker#504]
When the var KAFKA_JMX_OPTS is passed in a envfile [1] kafka doesn't start, from docker logs:
```
Error: Could not find or load main class "-Dcom.sun.management.jmxremote
```

The same var with --env works perfectly.

[1] https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file

**Comment by sscaling** [comment]
We explicitly ignore this var and don't process it (https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh#L121) -could this be a difference in how docker handles this? Judging by the error is it related to having the `=` sign in the value?

A quick test using the parameters from the README works fine for me:

**.env**

```
KAFKA_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=1099
```

**docker-compose.yml**

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092"
      - "1099:1099"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS:
      JMX_PORT: 1099
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

I can then connect fine over jconsole, e.g. `jconsole 127.0.0.1:1099`

If you can provide an example and steps to reproduce then we can take a look and try to rule out that it's anything with the kafka-docker image.
