### ISSUE TITLE
Unable to connect to the broker running on aws

### ISSUE THREAD

**Issue by vahuja4** [wurstmeister/kafka-docker#508]
I am using the single broker setup and have tried two different yml files. Please see below:

first try:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: <amazon_public_ip>
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


```
Second try:

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://ec2-xx-57-xx8-73.us-west-1.compute.amazonaws.com:9092

      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```
Port 9092 is open on the ec2 instance. But when I try to connect to the broker from my laptop, I am unable to. Can someone please help?
