### ISSUE TITLE
SSL in image

### ISSUE THREAD

**Issue by gg587998** [wurstmeister/kafka-docker#513]
Hi I tried too use a single broker with ssl to no avail.  Config is as follows:
I set LOCAL_IP kafka in my /etc/hosts. Basically same config with kafka_2.12-2.2.0.tgz is working.

I get the following error message when running the consumer

bin/kafka-console-producer.sh -broker-list kafka:9092 --topic test88 --producer.config config/client-ssl.properties                     

[2019-05-27 16:50:59,061] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 4 : {test88=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient)

```
security.protocol=SSL
ssl.truststore.location=/certs/docker.kafka.client.truststore.jks
ssl.truststore.password=<PASSWORD>
```

```
 version: '2'

 services:

  zookeeper:
    image: "wurstmeister/zookeeper:latest"
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
     - zookeeper
    ports:
     - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'SSL://kafka:9092'
      KAFKA_LISTENERS: 'SSL://0.0.0.0:9092'
      
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
 
     KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_SSL_KEYSTORE_LOCATION: '/certs/docker.kafka.server.keystore.jks'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'kafkadocker'
      KAFKA_SSL_KEY_PASSWORD: 'kafkadocker'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/certs/docker.kafka.server.truststore.jks'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'kafkadocker'
      # KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: 'SSL'
 

    volumes:
      - ./certs:/certs
```
