### ISSUE TITLE
Help - Setting custom CallbackHandler

### ISSUE THREAD

**Issue by filipstysiak** [wurstmeister/kafka-docker#515]
Hi,

I'm having problem setting custom CallbackHandler class for my Kafka. The idea is to override the SASL_PLAIN authentication with a custom one (checking usernames and password against Postgres database rather than the JAAS file).

Searching the web, I found that the way to do it (or at least the easiest approach) is to write a custom CallbackHandler (rather than overriding LoginModule). I tried so hard, and got so far, but in the end it doesn't even matter - the image won't get up.

my docker-compose
```yaml
version: "3.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      JVMFLAGS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    volumes:
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ./config/zoo.cfg:/opt/zookeeper-3.4.13/conf/zoo.cfg
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: SASL_PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_SUPER_USERS: User:admin
      KAFKA_SASL_CLIENT_CALLBACK_HANDLER_CLASS: app.security.sasl.PostgresDatabaseCallbackHandler # THIS DOESN'T WORK!!!
    depends_on:
      - zookeeper
    volumes:
      - ./config/callback.jar:/opt/kafka/bin/callback.jar
      - ./config/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
```
my class is in the callback.jar, starting with 
```java
package app.security.sasl
```
within it; The class refuses to be found.

Where did I make the mistake? I tried placing my jar in different places, but to no avail; is it a naming issue? Or maybe there's a better way to inject custom classes to this image?
