### ISSUE TITLE
There is no leader for this topic-partition as we are in the middle of a leadership election

### ISSUE THREAD

**Issue by thusfar7** [wurstmeister/kafka-docker#516]
I'm using kafka with KafkaJS. When I do `docker-compose up` everything works fine. But if I change any of the kafka configs or better to say, when kafka container restarts, my kafkajs nodejs code cannot send messages to topic nor listen from it and it throws the following error.

```
{"level":"ERROR","timestamp":"2019-07-02T18:27:28.585Z","logger":"kafkajs","message":"[Connection] Response Metadata(key: 3, version: 5)","broker":"kafka:9092","clientId":"test-2","error":"There is no leader for this topic-partition as we are in the middle of a leadership election","correlationId":5,"size":129}
```

But if I do `docker-compose down` and then `docker-compose up` then it works. Or more importantly, if I just do `docker rm -f project-name_zookeeper_1` and `docker-compose up` which recreates the zookeeper container then everything works fine again.

I also use kafkahq, which also works when my kafkajs/nodejs code works, and doesnt work when my kafkajs/nodejs code doesnt work. So I'd say the problem is not within that part of my app.

You could try to reproduce it yourself. Kafkahq password is **password**.

```
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - nw_kafka

  # Kafka
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    networks:
      - nw_kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "test-2:2:1,test-1:3:1"
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # KafkaHQ
  kafkahq:
    image: tchiotludo/kafkahq
    depends_on:
      - kafka
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
          security:
            basic-auth:
              root:
                password: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8'
                roles:
                  - topic/read
                  - topic/insert
                  - topic/delete
                  - topic/config/update
                  - node/read
                  - node/config/update
                  - topic/data/read
                  - topic/data/insert
                  - topic/data/delete
                  - group/read
                  - group/delete
                  - group/offsets/update
                  - registry/read
                  - registry/insert
                  - registry/update
                  - registry/delete
                  - registry/version/delete
            default-roles:
              - node/read
    ports:
      - 8089:8080
    networks:
      - nw_kafka
```

I searched through other people issues but haven't found a solution to this.

Any idea?
