### ISSUE TITLE
How to persist Kafka data after recreation?

### ISSUE THREAD

**Issue by thusfar7** [wurstmeister/kafka-docker#517]
I have a volume defined for my kafka container but everytime container is recreated I lose the data. As far as I noticed there is always a different logs dir created such as

kafka-logs-d3am33m
kafka-logs-3e22e2e2

How can I keep this consistent???

```
version: "3.7"

services:
  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    networks:
      - nw_kafka

  # Kafka
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    networks:
      - nw_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "test-1:1:1,test-2:1:1"
      KAFKA_TOPIC_METADATA_REFRESH_INTERVAL_MS: "60000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/kafka

volumes:
  postgres_data:
  kafka_data:
```
