### ISSUE TITLE
Kafka-docker cannot start using Docker Hub

### ISSUE THREAD

**Issue by nijatmursali** [wurstmeister/kafka-docker#523]
Hello, 

I have pulled the repository from [this](https://hub.docker.com/r/wurstmeister/kafka) link with 

> docker run --name kafka-docker -p 8585:8585 -d wurstmeister/kafka 

, but when I try to run kafka-docker with `docker run kafka-docker` it exits after few seconds. 

I'm using centOS 7 and I cannot find the `docker-compose.yml` after pulling from Docker Hub. 

Any reason why?

**Comment by sscaling** [comment]
Yes - docker hub hosts docker images, not arbitrary assets. If you want the docker-compose file you'll need to follow the link in the docker-hub README (e.g. https://raw.githubusercontent.com/wurstmeister/kafka-docker/master/docker-compose.yml). However, I'd recommend using the github [README](https://github.com/wurstmeister/kafka-docker/blob/master/README.md) as that is most up-to-date

**Comment by nijatmursali** [comment]
Thank you. So, I have to clone the repository and change the values by myself as well?

**Comment by sscaling** [comment]
No - that is your choice. However, the docker-compose file will need to exist somewhere  on your host - you can grab (curl/wget/copy & paste) the example file from the link and edit it to your requirements. If you wish to clone the repository that is your choice, but not required (only required if you want to build the image from scratch).

dockerhub hosts the pre-built images for distribution, docker-compose defines how to configure a container's runtime environment. 

If you want to use a pre-built image in your docker-compose file then just swap the `build` parameter to an `image` parameter, e.g.

```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

However, as per the README, you will likely need to configure the advertised host name / listener unless you are running docker toolbox for mac.

If you need more info on docker / docker-compose I suggest reading the [official docs](https://docs.docker.com/get-started/). To configure kafka you will need to understand it's operational requirements, so I suggest your read the [official docs](https://kafka.apache.org/documentation/). If you want to read about kafka connectivity in docker, the [Connectivity Guide](https://github.com/wurstmeister/kafka-docker/wiki/Connectivity) may be of use.

FYI - there is an open issue to update the docker hub README, but it's not something we have a lot of questions about. It's open 1year+ and doesn't even have a single 👍 (https://github.com/wurstmeister/kafka-docker/issues/373)
