### ISSUE TITLE
Setting up SASL PLAINTEXT configuration support

### ISSUE THREAD

**Issue by anuraagshah** [wurstmeister/kafka-docker#528]
I am trying to configure SASL plaintext with the following yaml
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,SSL://0.0.0.0:9093,SASL_PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka.test.com:9092,SSL://kafka.test.comm:9093,SASL_PLAINTEXT://kafka.test.com:9094
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

      KAFKA_SSL_KEYSTORE_LOCATION: '/var/private/ssl/server-keystore.p12'
      KAFKA_SSL_KEYSTORE_PASSWORD: 'cleversafe'
      KAFKA_SSL_KEY_PASSWORD: 'cleversafe'
      KAFKA_SSL_TRUSTSTORE_LOCATION: '/var/private/ssl/server-keystore.p12'
      KAFKA_SSL_TRUSTSTORE_PASSWORD: 'cleversafe'
      KAFKA_SSL_CLIENT_AUTH: 'none'

      KAFKA_SASL_ENABLED_MECHANISM: 'PLAIN'
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'

      KAFKA_CREATE_TOPICS: "anuraag:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
   volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/private/ssl/:/var/private/ssl/
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    extra_hosts:
      - "kafka.test.com:127.0.0.1"
```

and with the following kafka_server_jaas.conf in the same location as the yaml
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="ashah"
  user_admin="ashah";
};

KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="test"
  password="ashah";
};
```

In the docker-compose up output I see something 
```
kafka_1      | Excluding KAFKA_JMX_OPTS from broker config
kafka_1      | Excluding KAFKA_HOME from broker config
``` 

which then later fails as follow

```
kafka_1      | [2019-08-27 01:06:13,858] WARN SASL configuration failed: javax.security.auth.login.LoginException: No JAAS configuration section named 'Client' was found in specified JAAS configuration file: '/etc/kafka/kafka_server_jaas.conf'. Will continue connection to Zookeeper server without SASL authentication, if Zookeeper server allows it. (org.apache.zookeeper.ClientCnxn)

```

Any ideas/thoughts what I might be doing wrong here ?
