### ISSUE TITLE
Simple guide to enable SASL authentication between kafka broker  and client

### ISSUE THREAD

**Issue by vahuja4** [wurstmeister/kafka-docker#532]
I modified the file `docker-compose-single-broker.yml` to look like this:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    #network_mode: "bridge"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.31.16.54
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://172.31.16.54:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
      #- ./server.properties:/opt/kafka_2.12-2.2.1/config/server.properties
    links:
      - zookeeper

```
And, `kafka_server_jaas.conf` looks like below:
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret";
  user_admin="admin-secret"
  user_alice="alice-secret";
  security.protocol=SASL_PLAINTEXT
  sasl.mechanism=PLAIN
};
```
I am getting the following error:

```
kafka_1      | [2019-09-06 09:39:14,321] INFO Connecting to zookeeper on zookeeper:2181 (kafka.server.KafkaServer)
kafka_1      | [2019-09-06 09:39:14,331] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka_1      | org.apache.kafka.common.KafkaException: Exception while loading Zookeeper JAAS login context 'Client'
```
Can someone please explain if the above files look correct? Once again, I am not wanting any authentication between broker and zookeeper, rather I want broker-client authentication

**Comment by sscaling** [comment]
Have you read the [official documentation](https://kafka.apache.org/documentation/#brokerconfigs)? You have various conflicting configs (e.g. advertised.host.name and advertised.listeners)

The Kafka documentation covers [SASL configuration](https://kafka.apache.org/documentation/#security_sasl_config), if you're still struggling (and I've not tried it) but it looks like confluent have some fairly detailed guides on configuration SASL - https://docs.confluent.io/current/kafka/authentication_sasl/authentication_sasl_plain.html

If you're still having issues, review the server properties (printed out in the docker container logs at start up) to make sure they make sense. If there's not an issue with the image, and it's just broker administration then there's probably not much additional help we can provide. It is probably better to ask these questions on the Kafka mailing list - https://kafka.apache.org/contact

**Comment by swenzel** [comment]
Try changing your `kafka_server_jaas.conf` to:
```
KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin-secret"
  user_admin="admin-secret"
  user_alice="alice-secret";
};
Client {};
```
And the `docker-compose.yaml` to:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    links:
      - zookeeper
```

Then, after you've run `docker-compse up` and waited for the cluster to start up you can run:
```
-> kafkacat -b localhost:9092 -X security.protocol=SASL_PLAINTEXT -X sasl.mechanisms=PLAIN -X sasl.username=admin -X sasl.password=admin-secret -L
Metadata for all topics (from broker 1001: sasl_plaintext://localhost:9092/1001):
 1 brokers:
  broker 1001 at localhost:9092
 0 topics:
```

Setting up the connectivity correctly for more than one broker is a little more complicated. That's more or less covered in the wiki though.
