### ISSUE TITLE
Missing message when generated in chain of events in node application in same docker network

### ISSUE THREAD

**Issue by sonisaurabh19** [wurstmeister/kafka-docker#542]
I had been using CloudKarafka on a shared cluster setup with 2 topics for Node.js application. The use case was straightforward & it worked pretty well for me. 

Recently I starting running my node application(s) in docker containers and thought of setting up a local cluster for Kafka as well. Most things are fine, I am able to run some test messages through kafka-console-producer.sh and kafka-console-consumer.sh. Running it against my application is partially working. 

**Use case:** Application A1 is successfully sending a message, another application A2 in same docker network is successfully consuming it and successfully emitting new message which has to be consumed by application A3(this is where the problem is) in same docker network. There is no logging for the message once it is generated by A2 in application or Kafka and application A3 does not get/consume the message. So it looks like the message is lost/... after being generated by A2. However, if I send the message using kafka-console-producer.sh for application A3, it is consuming that message. 

docker-compose.yml
```
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka
    depends_on:
      - zookeeper        
    ports:
     - "9095:9095"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_PORT: 9095 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "start:1:3, end:1:3" 
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9095,OUTSIDE://kafka:9096
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://kafka:9095,OUTSIDE://kafka:9096
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
```

Application A1 emits message for topic 'start': 
```
const { Kafka } = require('kafkajs');
const kafka = new Kafka({
  brokers: ['kafka:9095']
});
const producer = kafka.producer();
await producer.connect();
await producer.send({
    topic: 'start',
    messages: [{ 
        value: xxx
    }]
});
```

Application A2 consumes 'start' and emits 'end': 
```
const kafka = new Kafka({
  brokers: ['kafka:9095']
});
const consumer = kafka.consumer({ groupId: '123' });
const run = async () => {
   await consumer.connect();
   await consumer.subscribe({ topic: 'start', fromBeginning: false });
   // application logic //
   await producer.send({
     topic: 'end',
      messages: [{ 
        value: yyy
    }]
  });
}
```

Application A3 has to consume 'end'.
```
const kafka = new Kafka({
  brokers: ['kafka:9095']
});
const consumer = kafka.consumer({ groupId: '456' });
const run = async () => {
   await consumer.connect();
   await consumer.subscribe({ topic: 'end', fromBeginning: false });
}
```

Any suggestions here.
