### ISSUE TITLE
KafkaConsumer not polling all messages

### ISSUE THREAD

**Issue by sandeepg86** [wurstmeister/kafka-docker#546]
I have a java code similar to the one below:

```
KafkaConsumer<Long, String> kafkaConsumer = new KafkaConsumer<>(properties);
partitions = Collections.singletonList(new TopicPartition(topic, partition));
kafkaConsumer.assign(partitions);
kafkaConsumer.seekToBeginning(List.of(partition));

ConsumerRecords<Long, String> records = kafkaConsumer.poll(Duration.ofMillis(pollDuration));
```

While running the code, I am not able to get all the messages in this particular topic. For example, if I have 24 records in this partition, I am able to get only 20 records.

This issue does not happen always. When we make Kafka (wurstmeister/kafka:1.1.0) up using docker in the same machine in which my application runs, I am able to get all records from that particular partition.

But when I make the same docker-compose up in another machine and connect to it, this issue happens.

Following is my docker-compose snippet:

```
zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka:1.1.0
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
      HTTP_PROTOCOL: http
    depends_on:
      - "zookeeper"
```
