### ISSUE TITLE
can't connect by other docker container

### ISSUE THREAD

**Issue by ilaipi** [wurstmeister/kafka-docker#560]
I start kafka server by docker-compose:

```
zk:
    image: zookeeper:3.4.9
    container_name: zk
    ports:
      - "42103:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_SERVERS: server.1=0.0.0.0:2888:3888
    volumes:
      - /data/lib/zoo/data:/data
      - /data/lib/zoo/datalog:/datalog

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka
    environment:
        - KAFKA_ADVERTISED_PORT=42104
        - KAFKA_ADVERTISED_HOST_NAME=my_public_ip
        - KAFKA_ZOOKEEPER_CONNECT=my_internal_ip:42103
        - KAFKA_LOG_RETENTION_HOURS=4
        - KAFKA_LOG_RETENTION_BYTES=1000000000
    ports:
        - 42104:9092
```

and then I start my node app in docker by:

```
docker run --env-file .env --env NODE_REPO=mr -p 34171:6000 -dit --restart always --name=mr_dev mr:0.0.1
```

in my node app, I connect kafka by kafka-node:

```
import Kafka from 'kafka-node';
const client = new Kafka.KafkaClient({kafkaHost: 'my_public_ip:42104'});
```

when I start node, it hang up. If I stop the kafka, my node server end with the error:
```
NestedError: refreshBrokerMetadata failed
    at async.waterfall (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:378:35)
    at /app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:473:16
    at next (/app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:5329:29)
    at /app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:969:16
    at KafkaClient.getAvailableBroker (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:330:12)
    at async.waterfall.callback (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:373:23)
    at nextTask (/app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:5334:5)
    at KafkaClient.refreshBrokerMetadata (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:372:9)
    at Immediate._onImmediate (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:782:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Caused By: Error: Unable to find available brokers to try
    at KafkaClient.getAvailableBroker (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:330:21)
    at async.waterfall.callback (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:373:23)
    at nextTask (/app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:5324:14)
    at Object.waterfall (/app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:5334:5)
    at KafkaClient.refreshBrokerMetadata (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:372:9)
    at Immediate._onImmediate (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:782:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at KafkaClient.<anonymous> (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/baseProducer.js:101:10)
    at KafkaClient.emit (events.js:198:13)
    at async.waterfall (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:378:21)
    at /app/node_modules/daoqun-core/node_modules/kafka-node/node_modules/async/dist/async.js:473:16
    [... lines matching original stack trace ...]
    at KafkaClient.refreshBrokerMetadata (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:372:9)
    at Immediate.<anonymous> (/app/node_modules/daoqun-core/node_modules/kafka-node/lib/kafkaClient.js:782:20)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

I don't know why, anybody have any idea?

thanks.
