### ISSUE TITLE
1 partitions have leader brokers without a matching listener

### ISSUE THREAD

**Issue by cherrylzhao** [wurstmeister/kafka-docker#566]
hi, all

I have pulled the latest images from `docker for Mac (18.06.1-ce)` , Kafka-docker started ok according to the docker-compose configuration. but when I start to write kafka message, then producer could not found a correct leader partition. after google I found this is for the  hostname configuration of advertised listener, even though I changed the `server.properties` of the hostname in the running Kafka docker container, this error could not be resolved.

my docker-compose setting is as below
```
version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka-2.12
    hostname: kafka.example.local
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka.example.local
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper-3.4
    hostname: zookeeper
    ports:
      - "2181:2181"l
```

also I have tried the following combination about advertised_host_name issue
```
    environment:
     HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181     
```
 
```
    environment:
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://_{HOSTNAME_COMMAND}:9092
      KAFKA_LISTENERS: OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181     
```

warning message from Kafka
```
[WARN ] 2020-01-28 17:13:16,656 --kafka-producer-network-thread | producer-1-- [org.apache.kafka.clients.NetworkClient] [Producer clientId=producer-1] 1 partitions have leader brokers without a matching listener, including [app-transaction-log-20191211-0]
```

very appreciate for your help !

**Comment by cricket007** [comment]
You don't really need to use the hostname command. 

Ref https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by cherrylzhao** [comment]
thanks very much @cricket007, you're right `HOSTNAME_COMMAND` is not needed.
this problem for me is wrong kafka topic created by the invalid environment configuration, so
leader partition could not been found. I have verified below config works fine.

```
version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka-2.12
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper-3.4
    hostname: zookeeper
    ports:
      - "2181:2181"
```
```
version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    container_name: kafka-2.12
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper-3.4
    hostname: zookeeper
    ports:
      - "2181:2181"
```
