### ISSUE TITLE
Ignoring partition count in auto create topics

### ISSUE THREAD

**Issue by tobyDickinson** [wurstmeister/kafka-docker#569]
I am running version `wurstmeister/kafka:2.12-2.4.0` and my `docker-compose.yml` file is below.

Docker Engine Version: 19.03.1

I understand that this is related to #490 however I am using `docker stack deploy`. I have tried deleting all volumes associated with this service (kafka, zookeeper) but this has failed to solve the issue.

```
version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - net
    deploy:
      restart_policy:
        condition: on-failure

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    networks:
      - net
    environment:
      KAFKA_CREATE_TOPICS: ingest:1:1,processing:10:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,<MY_HOST_IP>://:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_MAX_REQUEST_SIZE: 104857600
      KAFKA_MESSAGE_MAX_BYTES: 104857600
      KAFKA_REPLICA_FETCH_MAX_BYTES: 104857600
      KAFKA_FETCH_MESSAGE_MAX_BYTES: 104857600
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
      KAFKA_LOG_RETENTION_BYTES: 10737418240
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka:/kafka
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    depends_on:
      - zookeeper
    deploy:
      restart_policy:
        condition: on-failure
```

In my logs I am getting the following:

> ...
> creating topics: ingest:1:1
> creating topics: processing:10:1
> [2020-01-31 18:03:51,192] INFO Creating topic processing with configuration {} and initial partition assignment Map(0 -> ArrayBuffer(1001)) (kafka.zk.AdminZkClient)
> [2020-01-31 18:03:51,204] INFO [KafkaApi-1001] Auto creation of topic processing with 1 partitions and replication factor 1 is successful (kafka.server.KafkaApis)
> ...
