### ISSUE TITLE
Unable to consume message from kafka

### ISSUE THREAD

**Issue by coldray** [wurstmeister/kafka-docker#574]
Here is my Kafka-compose.yml file. I want to run two versions of Kafka on my local machine. 

```yml
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka0901:
    image: wurstmeister/kafka:2.11-0.9.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/0901"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

  kafka221:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9093:9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/221"
      KAFKA_LISTENERS: INSIDE://:9094,OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:SSL
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9094,OUTSIDE://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_SSL_KEYSTORE_LOCATION: somefilelocaltion
      KAFKA_SSL_KEYSTORE_PASSWORD: password
      KAFKA_SSL_TRUSTSTORE_LOCATION: somefilelocaltion
      KAFKA_SSL_TRUSTSTORE_PASSWORD: password
      KAFKA_SSL_CLIENT_AUTH: required
    volumes:
      - ./kafka/certs:/opt/kafka/certs
```yml

```docker-compose -f kafka-compose.yml up -d```
Then I started to send messages to both kafka
The one without SSL connection kafka works perfectly.
The one with SSL connection has some problems. From the application error log, there is some error:
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Failed to update metadata after 60000 ms.

Then I run bin/kafka-topics.sh --describe --zookeeper localhost:2181/221 --topic friends 
and got this error: 
```
Error while executing topic command : Failed to parse the broker info from zookeeper: {"listener_security_protocol_map":{"INSIDE":"PLAINTEXT","OUTSIDE":"SSL"},"endpoints":["INSIDE://1e13cab3d792:9094","OUTSIDE://localhost:9093"],"jmx_port":-1,"host":"1e13cab3d792","timestamp":"1583189025347","port":9094,"version":4}
[2020-03-02 15:16:49,739] ERROR kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"listener_security_protocol_map":{"INSIDE":"PLAINTEXT","OUTSIDE":"SSL"},"endpoints":["INSIDE://1e13cab3d792:9094","OUTSIDE://localhost:9093"],"jmx_port":-1,"host":"1e13cab3d792","timestamp":"1583189025347","port":9094,"version":4}
	at kafka.cluster.Broker$.createBroker(Broker.scala:85)
	at kafka.utils.ZkUtils.getBrokerInfo(ZkUtils.scala:763)
	at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:176)
	at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:176)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:176)
	at kafka.admin.TopicCommand$.describeTopic(TopicCommand.scala:187)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:66)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: java.lang.IllegalArgumentException: No enum constant org.apache.kafka.common.protocol.SecurityProtocol.INSIDE
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.apache.kafka.common.protocol.SecurityProtocol.valueOf(SecurityProtocol.java:27)
	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:48)
	at kafka.cluster.Broker$$anonfun$1.apply(Broker.scala:73)
	at kafka.cluster.Broker$$anonfun$1.apply(Broker.scala:72)
	at scala.collection.immutable.List.map(List.scala:273)
	at kafka.cluster.Broker$.createBroker(Broker.scala:72)
	... 13 more
 (kafka.admin.TopicCommand$)
```

It looks like something wrong when I created the Kafka cluster. Can someone help me check if it's something wrong with the yml file or anything else I need to take care of? Thanks in advance!
