### ISSUE TITLE
Possibility to access kafka contaner from other container

### ISSUE THREAD

**Issue by Sabutobi** [wurstmeister/kafka-docker#575]
I'm trying to do a connection between two containers via the message queue:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'someTopic:1:1:compact'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Kafka used as an alias. So I'm connected to 2 networks:
```
version: '3'
services:
  myservice:
    build:
        context: .
    image: myimage:latest
    ports:
    - "some_external:some_port"
    external_links:
      - mongoservice:${mongo_host}
      - kafka-docker_kafka_1:${kafka_host}
    container_name: some_container
    networks:
      - some_other_network
      - kafka-docker_default

networks:
    some_other_network:
      external: true
    kafka-docker_default:
      external: true
```

I can access to kafka consumer / producer if I'll use my services not packed in docker.
But what done wrong with settings of kafka docker container that it cannot be accessed from another container. 
![Screenshot from 2020-03-03 15-59-03](https://user-images.githubusercontent.com/12499311/75782754-18aa0900-5d68-11ea-989f-3fd1f912b86b.png)
![Screenshot from 2020-03-03 15-59-50](https://user-images.githubusercontent.com/12499311/75782772-1f388080-5d68-11ea-8436-da7ac5e088e5.png)

**Comment by Sabutobi** [comment]
Hi, once more.
I resolved issue with this config
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
     - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: 'Sometopic:1:1'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
```
**Main thoughts:** I do not know is that the best solution but I've downgraded version of kafka's docker image and added INSIDE/OUTSIDE things.
So at this moment, I have a connection from Host machine via `localhost:9092` and from docker container via `kafka:9093`
Solution got from [here](https://medium.com/big-data-engineering/hello-kafka-world-the-complete-guide-to-kafka-with-docker-and-python-f788e2588cfc). Maybe that will be helpful for someone.
