### ISSUE TITLE
Add MirrorMaker image?

### ISSUE THREAD

**Issue by ioreskovic** [wurstmeister/kafka-docker#582]
Would it be possible to add a MirrorMaker image?
Something you could use in this fashion:

```yaml
version: '3.2'
services:
  # zookeper & kafka definitions
  ...
  mirrormaker:
    image: mirrormaker:2.12-2.4.1
    depends_on:
      - kafka_primary_1
      - kafka_primary_2
      - kafka_primary_3
      - kafka_secondary_1
      - kafka_secondary_2
      - kafka_secondary_3
    volumes:
      - type: bind
        source: ./mm2.properties
        target: /opt/kafka/bin/mm2.properties
    restart: always
```

I've modified your `wurstmeister/kafka` image so it starts MirrorMaker instead, and it works, but I lack the experience and skills to make it production ready.
