### ISSUE TITLE
Enabling JMX for monitoring: KAFKA_JMX_OPTS is excluded

### ISSUE THREAD

**Issue by david-haemmerle** [wurstmeister/kafka-docker#584]
Hi, I use your Docker image to setup Kafka cluster for our internal test enviroment. That works fine so far. I'd like to enable JMX on a Kafka broker in order to retrieve metrics via **jconsole** (openJDK 11). However, jconsole always reports
`The connection to <IP address>:9997 did not succeed.`

In the logs I only found the line
`Excluding KAFKA_JMX_OPTS from broker config`
No indication why it was excluded. Even if I just set
`JMX_PORT: 9997`
(+ port mapping) in the Docker Compose file, the jconsole connection fails.

I'd appreciate greatly if someone could point out what I am doing wrong. Docker Compose file and logs are attached (some info is obfuscated). In general, I think it would be useful to explain in the FAQ or Wiki how to configure JMX for the Wurstmeister Docker image and, if possible, how to troubleshoot it.

Machine: Linux VM (Ubuntu 18.04.4 LTS "Bionic Beaver")

Docker Compose file:
```yaml
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MAX_CLIENT_CNXNS: 0

  kafka_1:
    # build: .
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.11.22:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote.port=9997 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false

      ############################# Internal Topic Settings  #############################
      
      # The replication factor for the group metadata internal topics "__consumer_offsets" and "__transaction_state"
      # For anything other than development testing, a value greater than 1 is recommended for to ensure availability such as 3.

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      ############################# Group Coordinator Settings #############################
      
      # The following configuration specifies the time, in milliseconds, that the GroupCoordinator will delay the initial consumer rebalance.
      # The rebalance will be further delayed by the value of group.initial.rebalance.delay.ms as new members join the group, up to a maximum of max.poll.interval.ms.
      # The default value for this is 3 seconds.
      # We override this to 0 here as it makes for a better out-of-the-box experience for development and testing.
      # However, in production environments the default value of 3 seconds is more suitable as this will help to avoid unnecessary, and potentially expensive, rebalances during application startup.

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka_2:
    # build: .
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.11.22:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
```

Docker Compose log:
[2020-03-30_kafka_with_jmx.log](https://github.com/wurstmeister/kafka-docker/files/4404407/2020-03-30_kafka_with_jmx.log)
