### ISSUE TITLE
Kafka scaling access to consumer

### ISSUE THREAD

**Issue by LucasRodriguez** [wurstmeister/kafka-docker#594]
Firstly, I realize this question has been asked a fair amount of times, but I don't feel any of the answers are verbose enough to actually help a person trying to navigate the issue. 

Im trying to scale up kafka by using the command:
`docker-compose scale kafka=3`

With the docker-compose file looking like:
```
zookeeper:
  image: wurstmeister/zookeeper
  container_name: zookeeper
  ports:
    - 2181
  networks:
    - titan_backend

kafka:
  image: wurstmeister/kafka:latest
  restart: always
  depends_on:
    - zookeeper
  ports:
    - 9092
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.1.25 #my host IP, by doing ipconfig getifaddr en0
      KAFKA_CREATE_TOPICS: "backtest:1:3, requestState:1:3, price:1:3, positions:1:3, margin:1:3, orders:1:3, leverage:1:3"
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:delegated
  networks:
    - titan_backend
```

This seems to work since I get three instances of kafka spun up:
```
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                         PORTS                                                 NAMES
8aa49c38afbf        wurstmeister/kafka:latest    "start-kafka.sh"         7 minutes ago       Up 7 minutes                   0.0.0.0:33084->9092/tcp                               backend_kafka_2
3b74c348deef        wurstmeister/kafka:latest    "start-kafka.sh"         7 minutes ago       Up 7 minutes                   0.0.0.0:33083->9092/tcp                               backend_kafka_1
a9adafe4baf2        wurstmeister/kafka:latest    "start-kafka.sh"         7 minutes ago       Up 6 minutes                   0.0.0.0:33085->9092/tcp                               backend_kafka_3
```

Within the containers, I get among a lot of logs:
```
creating topics: backtest:3:3
creating topics:  requestState:3:3
creating topics:  price:3:3
creating topics:  positions:3:3
creating topics:  margin:3:3
creating topics:  orders:3:3
creating topics:  leverage:3:3
Created topic margin.
Created topic positions.
Created topic orders.
Created topic requestState
Created topic leverage.
Created topic backtest.
Created topic price.
```

Given how the topics have been created I would expect to have one partition replicated through out the three brokers. Meaning if I ever call any given broker Kafka will find the leader one for me and produce or consume the right information. 

**Consuming**:
Im now using kafka-node  to consume from the topic. Keep in mind I should be able to alway refer to a given IP or host since I cant manually keep track every time I set up kafka. Therefore I do:
```
var kafka = require('kafka-node'),
    Consumer = kafka.Consumer,
    client = new kafka.KafkaClient({ kafkaHost: '192.168.1.25:9092' }), //I try to connect by using the host IP and the exposed docker port
    offset = new kafka.Offset(client)
```

This does not work I have tried several combinations, but cant seem to get it right. What exactly should I be connecting to? I have to assume there is a non-dynamic variable or hostname or even a constant IP, that I can use.

For the time being and with those inputs the response I get is:
`Error: connect ECONNREFUSED  192.168.1.25:9092`

Any guidance on how to better understand what I should be targeting would be super appreciated.

TIA
