### ISSUE TITLE
restart kafka error

### ISSUE THREAD

**Issue by zhangguijian** [wurstmeister/kafka-docker#597]
**frist start kafka it's ok
but when i try to stop kafka and restart  it,occur error**
`kafka2       | /usr/bin/start-kafka.sh: line 149: /opt/kafka/bin/kafka-server-start.sh: No such file or directory`
**so,this is  common? i can't restat docker kafka?
my sevice is centos, memeroy left 1G
this is my config**

```
`version: '2'
services:

  kafka2:
    image: wurstmeister/kafka
    restart: always
    hostname: kafka2
    container_name: kafka2
    ports:
    - "9093:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://120.79.57.121:9093
      KAFKA_ADVERTISED_HOST_NAME: 120.79.57.121
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        ipv4_address: 172.23.0.15



networks:
  default:
    external:
      name: zookeeper_network`
```
