### ISSUE TITLE
Cannot build Kafka from docker-compose-single-broker.yml

### ISSUE THREAD

**Issue by Prem-the-Builder** [wurstmeister/kafka-docker#603]
Hello,
I tried to build Kafka using _docker-compose-single-broker.ym_, but got this error:

`[wae@docker kafka-docker]$ docker-compose -f ./docker-compose-single-broker.yml up -d
Building kafka
Step 1/16 : FROM anapsix/alpine-java
 ---> c45785c254c5
Step 2/16 : ARG kafka_version=1.0.0
 ---> Using cache
 ---> e90e3d4ef82c
Step 3/16 : ARG scala_version=2.12
 ---> Using cache
 ---> 3c5f7d22861e
Step 4/16 : MAINTAINER wurstmeister
 ---> Using cache
 ---> 9b0112c308f3
Step 5/16 : RUN apk add --update unzip wget curl docker jq coreutils
 ---> Using cache
 ---> 52d47d78c5e1
Step 6/16 : ENV KAFKA_VERSION=$kafka_version SCALA_VERSION=$scala_version
 ---> Using cache
 ---> b94fe2ed51a2
Step 7/16 : ADD download-kafka.sh /tmp/download-kafka.sh
 ---> Using cache
 ---> 3f4713721a58
Step 8/16 : RUN chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka
 ---> Running in 6c2ec5c5c292
ERROR: Service 'kafka' failed to build: The command '/bin/sh -c chmod a+x /tmp/download-kafka.sh && sync && /tmp/download-kafka.sh && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} /opt/kafka' returned a non-zero code: 8
[wae@docker kafka-docker]$ `

The composer file is not modified much. I changed only service port and advertised host address:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.58.244.189
      KAFKA_CREATE_TOPICS: "telemetry"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Any pointer is highly appreciated.
