### ISSUE TITLE
How to persist data in docker swarm mode

### ISSUE THREAD

**Issue by hustlibraco** [wurstmeister/kafka-docker#604]
I deploy a Kafka cluster with two broker and one zookeeper in swarm mode. Firstly it works fine. After I restart kafka service, it will report error:
```
[2020-06-13 05:03:27,831] WARN [Producer clientId=console-producer] 2 partitions have leader brokers without a matching listener, including [var_log-0, var_log-1] (org.apache.kafka.clients.NetworkClient)
```

I find kafka broker id changed after restart, and zookeeper still store the old broker data. Maybe this data-out-sync cause this problem.

Here is my docker-compose.yaml:
```
zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - ember
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.type==kafka"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "var_log:2:2"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data00/kafka:/kafka
    networks:
      - ember
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.type==kafka"
```

So is there a way to persis kafka data in docker swarm mode? 
My demand is that when I restart all services(kafka & zookeeper), the external kafka consumer can still continue to get data from the offset before the service was interrupted

**Comment by OneCricketeer** [comment]
You must assign a broker ID. That way it will not be created for you.

Why not use k3s and Helm Charts, though, where all this is already figured out?

**Comment by hustlibraco** [comment]
> Why not use k3s and Helm Charts, though, where all this is already figured out?

Appreciate that. Although I have solved the problem by referring to the documentation(https://github.com/wurstmeister/kafka-docker/issues/263#issuecomment-389447168), I think this solution is not good enough. can you give me more info about kafka in k3s?

**Comment by hustlibraco** [comment]
Resolved. But not elegant.
```
  zookeeper:
    image: zookeeper:3.6.1
    ports:
      - "2181:2181"
    networks:
      - ember
    volumes:
      - /data00/zookeeper/data:/data
      - /data00/zookeeper/datalog:/datalog
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.labels.zookeeper==on"

  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    depends_on:
      - zookeeper
    ports:
      - target: 9094
        published: 9094
        protocol: tcp
        mode: host
    environment:
      # HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      HOSTNAME_COMMAND: "docker info -f '{{`{{.Swarm.NodeAddr}}`}}'"
      # BROKER_ID_COMMAND : "docker info -f '{{`{{.Name}}`}}' | sed 's/kafka//g'"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data00/kafka:/kafka
    networks:
      - ember
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.type==kafka"
```
