### ISSUE TITLE
Unable to connect to zookeeper on different port

### ISSUE THREAD

**Issue by egor-moysevich** [wurstmeister/kafka-docker#615]
Hello!

I'm just trying to launch kafka container which points to another zookeeper port.

When it is configured with `KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181` - all fine. 
But when i'm trying to use another port, e.g. 2183 it fails with error:
`Socket error occurred: zookeeper/X.X.X.X:2183: Connection refused (org.apache.zookeeper.ClientCnxn)`

Am i missing smth?

i've the following configuration of compose:
  ```
version: '3.4'

kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_PORT: 9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2183
      KAFKA_CREATE_TOPICS: >
        kafka_topic:1:1
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2181"
```

Will appreciate any help,
Thanks
