### ISSUE TITLE
Kafka consumer not reading topic messages 

### ISSUE THREAD

**Issue by Luis-cruz-DTx** [wurstmeister/kafka-docker#630]
Hi,

I have cluster with three kafka brokers and a single zookeeper. I have a producer with automatic topic creation. I want to have the producer with `acks=all`, `KAFKA_DEFAULT_REPLICATION_FACTOR: 3` and `KAFKA_MIN_INSYNC_REPLICAS: 2`. 

If I use default values, all seems fine. If I change the replication values mentioned above, but maintaining `acks=1`. With this definition, the producer publishes on the topic, since running the command below shows offset increasing:

`kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list kafkaBroker1:9093 --topic new_analyzers --time -1` 

Running the command below will show the processed messages:

`kafka-console-consumer.sh --topic new_analyzers --from-beginning --bootstrap-server kafkaBroker1:9093`

However, changing the acknowledgement to `acks=all` stops any message to be published to the broker.

**docker-compose file:**

```yaml
zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper 
        ports:
            - '2181:2181'       
        networks:
            - esardine-demo
kafkaBroker1:
        depends_on: 
            - zookeeper
        image: wurstmeister/kafka
        container_name: kafkaBroker1
        ports:
            - '19092:19092'
        hostname: kafkaBroker1
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkaBroker1:9093, OUTSIDE://localhost:19092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:19092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - esardine-demo
    kafkaBroker2:
        depends_on: 
            - zookeeper
        image: wurstmeister/kafka
        container_name: kafkaBroker2
        ports:
            - '29092:29092'
        hostname: kafkaBroker2
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkaBroker2:9093, OUTSIDE://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:29092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - esardine-demo
    kafkaBroker3:
        depends_on: 
            - zookeeper
        image: wurstmeister/kafka
        container_name: kafkaBroker3
        ports:
            - '39092:39092'
        hostname: kafkaBroker3
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkaBroker3:9093, OUTSIDE://localhost:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:39092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_MIN_INSYNC_REPLICAS: 2
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - esardine-demo
```

```console
kafka-topics.sh --describe --topic new_analyzers --bootstrap-server kafkaBroker1:9093
Topic: new_analyzers    PartitionCount: 1       ReplicationFactor: 3    Configs: min.insync.replicas=2,segment.bytes=1073741824
        Topic: new_analyzers    Partition: 0    Leader: 1003    Replicas: 1003,1001,1002        Isr: 1003,1001,1002

```

**Logs:**

```log
kafkaBroker1              | [2020-12-17 16:19:34,473] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-3. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-18. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-37. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-7. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-22. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-10. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-33. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-48. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-19. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-34. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-4. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-45. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-15. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-30. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-49. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-0. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-39. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-9. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-24. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-27. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-42. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-12. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-31. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-46. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-1. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-16. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-21. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-36. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-6. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-25. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,474] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-40. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,475] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-43. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,475] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-13. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,475] INFO [GroupMetadataManager brokerId=1001] Finished unloading __consumer_offsets-28. Removed 0 cached offsets and 0 cached groups. (kafka.coordinator.group.GroupMetadataManager)
kafkaBroker1              | [2020-12-17 16:19:34,938] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-16 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-13 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-46 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-43 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-10 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-22 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-19 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-49 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-31 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-28 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-25 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-7 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,949] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-40 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,950] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-37 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,950] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-4 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,950] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-1 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
kafkaBroker1              | [2020-12-17 16:19:34,950] ERROR [ReplicaFetcher replicaId=1001, leaderId=1003, fetcherId=0] Error for partition __consumer_offsets-34 at offset 0 (kafka.server.ReplicaFetcherThread)
kafkaBroker1              | org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.

```
