### ISSUE TITLE
Multiple Zookeeper - NoNode errors

### ISSUE THREAD

**Issue by psdon** [wurstmeister/kafka-docker#633]
### docker-compose.yml
```
version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      DOCKER_GATEWAY_HOST: 172.17.0.1
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_GATEWAY_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper 
    depends_on:
      - zookeeper
```

### Logs
```
kafka_1      | [2020-12-22 22:24:22,907] INFO Socket connection established, initiating session, client: /192.168.128.3:37336, server: zookeeper/192.168.128.2:2
181 (org.apache.zookeeper.ClientCnxn)
zookeeper_1  | 2020-12-22 22:24:22,907 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@215] - Accepted socket connection from /1
92.168.128.3:37336
zookeeper_1  | 2020-12-22 22:24:22,933 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@949] - Client attempting to establish new sess
ion at /192.168.128.3:37336
zookeeper_1  | 2020-12-22 22:24:22,942 [myid:] - INFO  [SyncThread:0:FileTxnLog@213] - Creating new log file: log.1
zookeeper_1  | 2020-12-22 22:24:22,990 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@694] - Established session 0x100012c24920000 with negotiated timeout 18000

zookeeper_1  | 2020-12-22 22:17:47,491 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@653] - Got user-level KeeperException when proces$
ing sessionid:0x10001261cd10000 type:create cxid:0x2 zxid:0x3 txntype:-1 reqpath:n/a Error Path:/brokers Error:KeeperErrorCode = NoNode for /brokers
zookeeper_1  | 2020-12-22 22:17:47,519 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@653] - Got user-level KeeperException when proces$
ing sessionid:0x10001261cd10000 type:create cxid:0x6 zxid:0x7 txntype:-1 reqpath:n/a Error Path:/config Error:KeeperErrorCode = NoNode for /config
zookeeper_1  | 2020-12-22 22:17:47,540 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@653] - Got user-level KeeperException when proces$
ing sessionid:0x10001261cd10000 type:create cxid:0x9 zxid:0xa txntype:-1 reqpath:n/a Error Path:/admin Error:KeeperErrorCode = NoNode for /admin
zookeeper_1  | 2020-12-22 22:17:47,912 [myid:] - INFO  [ProcessThread(sid:0 cport:2181)::PrepRequestProcessor@653] - Got user-level KeeperException when proces$
ing sessionid:0x10001261cd10000 type:create cxid:0x15 zxid:0x15 txntype:-1 reqpath:n/a Error Path:/cluster Error:KeeperErrorCode = NoNode for /cluster
```
