### ISSUE TITLE
access single broker from inside and outside on random port

### ISSUE THREAD

**Issue by ravenblackdusk** [wurstmeister/kafka-docker#638]
I have successfully been able to do what I want on a specific outside port; But since I'm trying to run tests, I need the outside access to be on a random port. This is what I've come up with:
```
  zookeeper:
    restart: unless-stopped
    logging:
      options:
        max-size: 1m
        max-file: "1"
    image: zookeeper:latest
    environment:
      TZ: ${TZ}
  kafka:
    restart: unless-stopped
    logging:
      options:
        max-size: 1m
        max-file: "1"
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:latest
    environment:
      PORT_COMMAND: "docker port $$(hostname) 9092/tcp | cut -d: -f2"
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://localhost:_{PORT_COMMAND},INSIDE://:9092
      KAFKA_LISTENERS: OUTSIDE://:_{PORT_COMMAND},INSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_CREATE_TOPICS: "xxxx"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092"
```
But my outside producer complains about not being able to resolve <seemingly random id>. Debugging reveals that my producer is tyring to connect to both `localhost:<random port>` and `<seemingly random id>:9092`. Judging by the 9092 perhaps the `INSIDE` advertised listener is being advertised for outside connections...
