### ISSUE TITLE
Can't run kafka container - sed: unmatched '@'

### ISSUE THREAD

**Issue by marcelohweb** [wurstmeister/kafka-docker#652]
Hi,

I'm using a simple docker-compose configuration:

```
version: "3.4"

services:

    zookeeper:
      image: zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: wurstmeister/kafka:2.12-2.5.0
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_MESSAGE_MAX_BYTES: 104858800
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    kafka-web-gui:
      image: tchiotludo/akhq
      ports:
        - "8081:8080"
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              docker-kafka-server:
                properties:
                  bootstrap.servers: "kafka:9092"

```

My stack is running without any problem in the first execution. But, when I try to run the kafka container again, I get the following error:

kafka_1          | [Configuring] 'advertised.port' in '/opt/kafka/config/server.properties'
kafka_1          | sed: unmatched '@'
kafka-deployment_kafka_1 exited with code 1

I use ubuntu 20.04
Docker version 20.10.6, build 370c289
docker-compose version 1.26.0, build d4451659

**Comment by JoBergs** [comment]
Hello,

i'm experiencing the same error on

Linux version 5.4.0-72-generic (buildd@lcy01-amd64-019) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021
----------------------------------------------
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        370c289
 Built:             Fri Apr  9 22:47:17 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
----------------------------------------------
docker-compose version 1.27.4, build 40524192

With the Dockerfile
```
FROM openjdk:8u212-jre-alpine

ARG kafka_version=2.4.0
ARG scala_version=2.12
ARG glibc_version=2.30-r0
ARG vcs_ref=unspecified
ARG build_date=unspecified

LABEL org.label-schema.name="kafka" \
      org.label-schema.description="Apache Kafka" \
      org.label-schema.build-date="${build_date}" \
      org.label-schema.vcs-url="https://github.com/wurstmeister/kafka-docker" \
      org.label-schema.vcs-ref="${vcs_ref}" \
      org.label-schema.version="${scala_version}_${kafka_version}" \
      org.label-schema.schema-version="1.0" \
      maintainer="wurstmeister"

ENV KAFKA_VERSION=$kafka_version \
    SCALA_VERSION=$scala_version \
    KAFKA_HOME=/opt/kafka \
    GLIBC_VERSION=$glibc_version

ENV PATH=${PATH}:${KAFKA_HOME}/bin

COPY download-kafka.sh start-kafka.sh broker-list.sh create-topics.sh versions.sh /tmp/

RUN apk add --no-cache bash curl jq docker \
 && chmod a+x /tmp/*.sh \
 && mv /tmp/start-kafka.sh /tmp/broker-list.sh /tmp/create-topics.sh /tmp/versions.sh /usr/bin \
 && sync && /tmp/download-kafka.sh \
 && tar xfz /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz -C /opt \
 && rm /tmp/kafka_${SCALA_VERSION}-${KAFKA_VERSION}.tgz \
 && ln -s /opt/kafka_${SCALA_VERSION}-${KAFKA_VERSION} ${KAFKA_HOME} \
 && rm /tmp/* \
 && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk \
 && apk add --no-cache --allow-untrusted glibc-${GLIBC_VERSION}.apk \
 && rm glibc-${GLIBC_VERSION}.apk

COPY overrides /opt/overrides

VOLUME ["/kafka"]

# Use "exec" form so that it runs as PID 1 (useful for graceful shutdown)
CMD ["start-kafka.sh"]
```
Could this be related to some recent changes in Alpine?

**Comment by T-Berger** [comment]
+1 get the same error messages

**Comment by linhx** [comment]
```yml
version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_MESSAGE_MAX_BYTES=2000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - kafka

networks:
  kafka:
    external:
      name: microservivegs
```
This is my `docker-compose.yaml`.
1. I run `sudo docker-compose up --build` for the first time, it was working well.
2. After stop it, I run `sudo docker-compose up`, I got the error too.

Cuz the error shows something about `advertised.port`. So I specify the advertised port = 8092. It's working well.
```yml
...
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - ...
```

--------
For more information:
After I got the error, if I change some environment variable (e.g. `- KAFKA_CREATE_TOPICS="Topic1:1:1"`) and run `sudo docker-compose up --build` again. The kafka can start without the error. **But my code doesn't work any more** (the consumer can't receive the data). After that I need to remove the Kafka container and the Zookeeper container and re-build.
