### ISSUE TITLE
The volume of kafka is big

### ISSUE THREAD

**Issue by huwentao1** [wurstmeister/kafka-docker#719]
this is my kakfa volume size
<img width="391" alt="image" src="https://user-images.githubusercontent.com/43719888/185018498-b0a60a64-8cc1-4ca9-9b3a-631e72f363e4.png">

this is my docker-compose file,
```
version: "3.1"
services:
  zoo1:
    image: zookeeper:3.4.13
    restart: always
    hostname: zoo1
    container_name: zk1
    ports:
      - 2181:2181
    volumes:
      - /xxx/kfk/zookeeper/zoo1/data:/data
      - /xxx/kfk/zookeeper/zoo1/datalog:/datalog
  kfk1:
    image: wurstmeister/kafka:2.11-0.10.2.1
    restart: always
    hostname: kfk1
    container_name: kfk1
    ports:
      - "9091:9091"
    depends_on:
      - zoo1
    environment:
      KAFKA_HEAP_OPTS: "-Xmx4G -Xms4G"
      KAFKA_BROKER_ID: 1
      KAFKA_MESSAGE_MAX_BYTES: 60000000
      KAFKA_OREPLICA_FETCH_MAX_BYTES: 80000000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: PLAINTEXT://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://x.x.x.x:9091
    volumes:
      - /xxx/kfk/kafka/docker.sock:/var/run/docker.sock
```
I read in the document that messages will be deleted by default after 7 days, so I don't know why my volume is getting bigger and bigger
