### ISSUE TITLE
Publishing zookeeper

### ISSUE THREAD

**Issue by jconlon** [wurstmeister/kafka-docker#75]
In the docker-compose.yml the configuration for zookeeper:

```
zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181"
```

Since we only will have one zookeeper why expose but not map the 2181 to a host port?  
  as  "2181:2181"
