### ISSUE TITLE
Could not start kafka service: service "kafka" is not running

### ISSUE THREAD

**Issue by Studio-tyx** [wurstmeister/kafka-docker#755]
when I want to start kafka service using:
```
$ sudo docker compose exec kafka kafka-console-consumer.sh --bootstrap-server kafka:9092 --topic SYS
```
the result shows that:
```
service "kafka" is not running
```

the docker-compose.yml is:
```
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    build: .
    ports:
      - "9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_ADVERTISED_HOST_NAME: 10.214.131.197
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
