### ISSUE TITLE
kafka message production with no exposed ports

### ISSUE THREAD

**Issue by ibizaman** [wurstmeister/kafka-docker#76]
Hello,

I just can't seem to make a producer produce messages when using only intra-docker network.
As far as I guess, this issue resolves around the `KAFKA_ADVERTISED_HOST_NAME` setting. Would you mind helping me here?
The exact problem is that I can connect to the kafka daemon but cannot produce to it. It seems to be the standard problem when `KAFKA_ADVERTISED_HOST_NAME` is not correctly set.

Here is my `docker-compose.yml`:
```yaml
    my-app:
        build: .
        links:
            - kafka

    zookeeper:
        image: wurstmeister/zookeeper

    kafka:
        image: wurstmeister/kafka
        links:
            - zookeeper:zk
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "192.168.1.10"
            #KAFKA_ADVERTISED_HOST_NAME: "kafka"
            #KAFKA_HOST_NAME: "192.168.1.10"
            #KAFKA_HOST_NAME: "kafka"
            #HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
```
With `192.198.1.10` the docker host internal ip.

I tried to play with `KAFKA_ADVERTISED_HOST_NAME`, `HOSTNAME_COMMAND` and `KAFKA_HOST_NAME` without success. Even completely disabling them.

One way to make it work is by exposing the internal ports:
```yaml
    my-app:
        build: .
        links:
            - kafka

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - 2181:2181

    kafka:
        image: wurstmeister/kafka
        links:
            - zookeeper:zk
        ports:
            - 9092:9092
        environment:
            KAFKA_ADVERTISED_HOST_NAME: "kafka"
            KAFKA_ADVERTISED_PORT: "9092"
            KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
```
... thing I would rather not do. But then at least the client can connect to `kafka:9092` and produce messages.
