### ISSUE TITLE
Support docker-compose version 2

### ISSUE THREAD

**Issue by mavencode01** [wurstmeister/kafka-docker#92]
Any plans to support docker compose version 2 ?

**Comment by greglanthier** [comment]
You can probably make the existing images work in docker-compose version 2 files, though your mileage may vary.

One problem you run into using docker-compose version '2' files to launch this image is the fact that shell scripts used in this image like `start-kafka.sh` rely on specific [environment variables](https://docs.docker.com/compose/link-env-deprecated/) that were set when linking images in docker-compose in version 1 files.  These environment files were used to populate Kafka configuration files and other bits of housekeeping.

These environment variables have been [deprecated](https://docs.docker.com/compose/link-env-deprecated/) for a while and are now removed when using docker-compose version 2 files.

You can override the settings that rely on these missing environment variables using the `environment:` section of the `docker-compose.yml` file.

For example:

```yml
version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:0.8.2.0
    ports:
      - "9092:9092"
    links:
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.10.50"
      KAFKA_CREATE_TOPICS: "dataload.job.queue:2:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
Note the `KAFKA_ZOOKEEPER_CONNECT` entry.  This will compel Kafka to use `zk:2181` as the Zookeeper connect string - which was enough to at least start the services in my development environment.

There may be other settings you'll need to override in your environment (which is why YMMV).  By scanning through [start-kafka.sh](https://github.com/wurstmeister/kafka-docker/blob/master/start-kafka.sh) you should be able to figure any missing `KAFKA_*` environment variables.

I hope that helps.
